<div class="space-y-4 lg:space-y-6">
    <section class="rounded-[10px] border border-slate-200 bg-white p-4 shadow-sm lg:p-6">
        <div class="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><h1 class="text-xl font-semibold text-slate-900 lg:text-2xl">İK Asistanı</h1><p class="mt-1 text-sm text-slate-500">Kaynak gösteren, yetki duyarlı ve yalnızca okuma yapan doğal dil çalışma alanı.</p></div><span class="rounded bg-emerald-50 px-2 py-0.5 text-xs font-mono text-emerald-700">Salt okunur</span></div>
        <div class="mt-4 rounded-[8px] border border-amber-200 bg-amber-50/70 p-3 text-xs text-amber-800">Asistan kayıt oluşturmaz, onaylamaz veya değiştirmez. Sağlık ve ücret sonuçları ayrıca yetkilendirilir; kişi bazlı hassas veri açıklanmaz.</div>
        @if($errors->any())<div class="mt-3 rounded-[8px] border border-red-200 bg-red-50 p-3 text-sm text-red-800">{{ $errors->first() }}</div>@endif
        <form wire:submit="ask" class="mt-4 flex flex-col gap-3 sm:flex-row"><textarea wire:model.defer="question" rows="2" class="min-w-0 flex-1 rounded-[6px] border border-slate-200 px-3 py-3 text-base sm:text-sm" placeholder="İK verileriniz hakkında toplulaştırılmış bir soru sorun"></textarea><button class="w-full rounded-[6px] bg-slate-900 px-4 py-3 text-sm text-white sm:w-auto sm:py-2" wire:loading.attr="disabled" wire:target="ask"><span wire:loading.remove wire:target="ask">Soruyu yanıtla</span><span wire:loading wire:target="ask">Hesaplanıyor…</span></button></form>
        <div class="mt-3 flex flex-wrap gap-2">@foreach($examples as $example)<button wire:click="useExample(@js($example))" class="rounded-[6px] border border-slate-200 bg-white px-3 py-2 text-xs text-slate-600">{{ $example }}</button>@endforeach</div>
    </section>

    <div class="grid grid-cols-1 gap-3 lg:gap-4 xl:grid-cols-12">
        <aside class="overflow-hidden rounded-[10px] border border-slate-200 bg-white shadow-sm xl:col-span-4"><div class="border-b border-slate-200 bg-slate-50/60 p-4"><h2 class="text-sm font-semibold">Soru geçmişim</h2><p class="text-xs text-slate-500">Yalnız sizin şifreli sorgularınız</p></div><div class="max-h-[560px] divide-y divide-slate-100 overflow-y-auto">@forelse($history as $row)<button wire:click="select({{ $row->id }})" class="w-full p-4 text-left hover:bg-slate-50/60 {{ $selectedQueryId === $row->id ? 'bg-slate-50' : '' }}"><p class="line-clamp-2 text-sm font-medium text-slate-800">{{ $row->queryText() }}</p><div class="mt-2 flex items-center justify-between gap-2"><span class="rounded bg-slate-100 px-2 py-0.5 text-xs font-mono">{{ $row->intent }}</span><time class="text-xs text-slate-400">{{ $row->created_at->format('d.m H:i') }}</time></div></button>@empty<p class="p-6 text-sm text-slate-500">Henüz soru yok.</p>@endforelse</div></aside>
        <section class="overflow-hidden rounded-[10px] border border-slate-200 bg-white shadow-sm xl:col-span-8">@if($selected)<div class="flex flex-col gap-2 border-b border-slate-200 bg-slate-50/60 p-4 sm:flex-row sm:items-center sm:justify-between"><div><p class="text-xs text-slate-500">Soru</p><h2 class="mt-1 text-sm font-semibold text-slate-900">{{ $selected->queryText() }}</h2></div><span class="rounded px-2 py-0.5 text-xs font-mono {{ $selected->status === 'denied' || $selected->status === 'blocked' ? 'bg-amber-50 text-amber-700' : 'bg-emerald-50 text-emerald-700' }}">{{ $selected->status }}</span></div><div class="p-4 lg:p-6"><p class="whitespace-pre-wrap text-sm leading-6 text-slate-800">{{ $selected->responseText() }}</p></div><div class="border-t border-slate-200 bg-slate-50/60 p-4"><p class="text-xs font-semibold uppercase tracking-wide text-slate-500">Kaynaklar</p><div class="mt-2 flex flex-wrap gap-2">@forelse($selected->sources as $source)<span class="rounded bg-white px-2 py-1 text-xs font-mono text-slate-600 ring-1 ring-slate-200">{{ $source }}</span>@empty<span class="text-xs text-slate-500">Bu yanıt veri kaynağı okumadı.</span>@endforelse</div></div>@else<p class="p-10 text-center text-sm text-slate-500">Bir soru sorarak başlayın.</p>@endif</section>
    </div>
</div>
