<?php

namespace App\Modules\Hr\Training\Livewire;

use App\Modules\Hr\Core\Services\TenantContext;
use App\Modules\Hr\Personnel\Models\HrEmployee;
use App\Modules\Hr\Training\Actions\CreateTrainingCourseAction;
use App\Modules\Hr\Training\Actions\EnrollTrainingEmployeeAction;
use App\Modules\Hr\Training\Actions\RecordTrainingResultAction;
use App\Modules\Hr\Training\Actions\ScheduleTrainingSessionAction;
use App\Modules\Hr\Training\Models\HrCertificate;
use App\Modules\Hr\Training\Models\HrTrainingCourse;
use App\Modules\Hr\Training\Models\HrTrainingEnrollment;
use App\Modules\Hr\Training\Models\HrTrainingSession;
use Livewire\Component;
use Livewire\WithPagination;

class TrainingWorkspace extends Component
{
    use WithPagination;

    public bool $selfService=false; public string $courseCode=''; public string $courseTitle=''; public string $courseCategory=''; public int $durationMinutes=60; public string $passingScore=''; public string $validityMonths=''; public bool $isMandatory=false; public ?int $courseId=null; public string $deliveryType='classroom'; public string $instructor=''; public string $location=''; public string $startsAt=''; public string $endsAt=''; public string $capacity=''; public ?int $sessionId=null; public ?int $employeeId=null; public array $progressValues=[]; public array $scoreValues=[]; public string $statusFilter=''; public string $sortField='created_at'; public string $sortDirection='desc'; public array $visibleColumns=['employee','course','session','progress','score','status','certificate','actions']; public const COLUMNS=['employee'=>'Çalışan','course'=>'Eğitim','session'=>'Oturum','progress'=>'İlerleme','score'=>'Sınav','status'=>'Durum','certificate'=>'Sertifika','actions'=>'İşlem']; private const SORTABLE=['created_at','progress_percent','exam_score','status'];

    public function mount(bool $selfService=false):void{$this->selfService=$selfService;$this->startsAt=now()->addWeek()->format('Y-m-d\TH:i');$this->endsAt=now()->addWeek()->addHour()->format('Y-m-d\TH:i');}
    public function createCourse(CreateTrainingCourseAction $action):void{$this->validate(['courseCode'=>'required|string|max:60','courseTitle'=>'required|string|max:180','durationMinutes'=>'required|integer|min:0','passingScore'=>'nullable|numeric|min:0|max:100','validityMonths'=>'nullable|integer|min:1']);$course=$action->execute(['code'=>$this->courseCode,'title'=>$this->courseTitle,'category'=>$this->courseCategory?:null,'duration_minutes'=>$this->durationMinutes,'passing_score'=>$this->passingScore===''?null:$this->passingScore,'certificate_validity_months'=>$this->validityMonths===''?null:$this->validityMonths,'is_mandatory'=>$this->isMandatory]);$this->courseId=$course->id;$this->reset(['courseCode','courseTitle','courseCategory','passingScore','validityMonths','isMandatory']);session()->flash('success','Eğitim kataloğa eklendi.');}
    public function scheduleSession(ScheduleTrainingSessionAction $action):void{$this->validate(['courseId'=>'required|integer','startsAt'=>'required|date','endsAt'=>'required|date','capacity'=>'nullable|integer|min:1']);$session=$action->execute($this->course($this->courseId),['delivery_type'=>$this->deliveryType,'instructor'=>$this->instructor?:null,'location'=>$this->location?:null,'starts_at'=>$this->startsAt,'ends_at'=>$this->endsAt,'capacity'=>$this->capacity===''?null:$this->capacity]);$this->sessionId=$session->id;session()->flash('success','Eğitim oturumu planlandı.');}
    public function enroll(EnrollTrainingEmployeeAction $action):void{$this->validate(['sessionId'=>'required|integer','employeeId'=>'required|integer']);$action->execute($this->session($this->sessionId),$this->employee($this->employeeId));session()->flash('success','Çalışan eğitime kaydedildi.');}
    public function recordResult(int $id,RecordTrainingResultAction $action):void{$progress=$this->progressValues[$id]??null;$score=$this->scoreValues[$id]??null;abort_unless(is_numeric($progress),422,'İlerleme oranı zorunludur.');$action->execute($this->enrollment($id),(int)$progress,$score===''||$score===null?null:(float)$score);unset($this->progressValues[$id],$this->scoreValues[$id]);session()->flash('success','Eğitim sonucu kaydedildi.');}
    public function sortTable(string $field):void{abort_unless(in_array($field,self::SORTABLE,true),422);if($this->sortField===$field)$this->sortDirection=$this->sortDirection==='asc'?'desc':'asc';else{$this->sortField=$field;$this->sortDirection='asc';}}
    public function toggleColumn(string $key):void{abort_unless(isset(self::COLUMNS[$key]),422);if(in_array($key,['employee','actions'],true))return;$this->visibleColumns=in_array($key,$this->visibleColumns,true)?array_values(array_diff($this->visibleColumns,[$key])):array_values(array_intersect(array_keys(self::COLUMNS),[...$this->visibleColumns,$key]));}
    public function render(){ $tenant=app(TenantContext::class)->getId();$own=$this->selfService?$this->ownEmployee():null;$query=HrTrainingEnrollment::withoutGlobalScope('tenant')->where('legal_entity_id',$tenant)->when($own,fn($q)=>$q->where('employee_id',$own->id))->when($this->statusFilter!=='',fn($q)=>$q->where('status',$this->statusFilter))->with(['employee','session.course','certificate']);return view('livewire.hr.training.training-workspace',['enrollments'=>$query->orderBy($this->sortField,$this->sortDirection)->paginate(20),'courses'=>HrTrainingCourse::withoutGlobalScope('tenant')->where('legal_entity_id',$tenant)->where('is_active',true)->orderBy('title')->get(),'sessions'=>HrTrainingSession::withoutGlobalScope('tenant')->where('legal_entity_id',$tenant)->where('status','scheduled')->withCount('enrollments')->with('course')->latest('starts_at')->get(),'employees'=>HrEmployee::withoutGlobalScope('tenant')->where('legal_entity_id',$tenant)->active()->orderBy('first_name')->get(),'certificates'=>HrCertificate::withoutGlobalScope('tenant')->where('legal_entity_id',$tenant)->when($own,fn($q)=>$q->where('employee_id',$own->id))->with(['employee','course'])->latest('issued_on')->limit(30)->get(),'columnLabels'=>self::COLUMNS])->layout('layouts.app');}
    private function course(?int $id):HrTrainingCourse{return HrTrainingCourse::withoutGlobalScope('tenant')->where('legal_entity_id',app(TenantContext::class)->getId())->findOrFail($id);} private function session(?int $id):HrTrainingSession{return HrTrainingSession::withoutGlobalScope('tenant')->where('legal_entity_id',app(TenantContext::class)->getId())->findOrFail($id);} private function employee(?int $id):HrEmployee{return HrEmployee::withoutGlobalScope('tenant')->where('legal_entity_id',app(TenantContext::class)->getId())->findOrFail($id);} private function enrollment(int $id):HrTrainingEnrollment{return HrTrainingEnrollment::withoutGlobalScope('tenant')->where('legal_entity_id',app(TenantContext::class)->getId())->findOrFail($id);} private function ownEmployee():HrEmployee{return HrEmployee::withoutGlobalScope('tenant')->where('legal_entity_id',app(TenantContext::class)->getId())->where('user_id',auth()->id())->firstOrFail();}
}
