<div class="space-y-4 lg:space-y-6">
<div class="flex flex-col sm:flex-row sm:items-start sm:justify-between gap-3"><div><h1 class="text-xl lg:text-2xl font-semibold text-slate-900">Brüt–Net Hesaplama Aracı</h1><p class="mt-1 text-sm text-slate-500">Onaylı ve yürürlükteki kural sürümüyle brütten nete veya netten brüte açıklanabilir simülasyon yapın.</p></div><a href="{{ route('hr.payroll') }}" class="w-full sm:w-auto px-4 py-3 sm:py-2 rounded-[6px] border border-slate-200 bg-white text-center text-sm">Bordro çalışma alanı</a></div>
<div class="grid grid-cols-1 xl:grid-cols-3 gap-3 lg:gap-4">
<form wire:submit="calculate" class="space-y-3 rounded-[10px] border border-slate-200 bg-white p-4 lg:p-6 shadow-sm">
<select wire:model.live="mode" class="w-full text-base sm:text-sm rounded-[6px] border border-slate-200 bg-white px-3 py-3 sm:py-2"><option value="gross_to_net">Brütten nete</option><option value="net_to_gross">Netten brüte</option></select>
<input type="number" step="0.01" min="0.01" wire:model.defer="amount" class="w-full text-base sm:text-sm rounded-[6px] border border-slate-200 px-3 py-3 sm:py-2" placeholder="{{ $mode==='net_to_gross'?'Hedef net':'Aylık brüt' }}">
<input type="number" step="0.01" min="0" wire:model.defer="openingTaxBase" class="w-full text-base sm:text-sm rounded-[6px] border border-slate-200 px-3 py-3 sm:py-2" placeholder="Devreden vergi matrahı">
<div class="grid grid-cols-1 sm:grid-cols-2 gap-3"><input type="number" min="1" wire:model.defer="scheduledMinutes" class="text-base sm:text-sm rounded-[6px] border border-slate-200 px-3 py-3 sm:py-2" placeholder="Planlanan dakika"><input type="number" min="0" wire:model.defer="missingMinutes" class="text-base sm:text-sm rounded-[6px] border border-slate-200 px-3 py-3 sm:py-2" placeholder="Eksik dakika"></div>
<input type="number" min="0" wire:model.defer="approvedOvertimeMinutes" class="w-full text-base sm:text-sm rounded-[6px] border border-slate-200 px-3 py-3 sm:py-2" placeholder="Onaylı fazla mesai dakika">
@if($errors->any())<p class="text-xs text-red-600">{{ $errors->first() }}</p>@endif
<button class="w-full sm:w-auto px-4 py-3 sm:py-2 rounded-[6px] bg-slate-900 text-sm text-white">Hesapla</button>
</form>
<section class="xl:col-span-2 rounded-[10px] border border-slate-200 bg-white p-4 lg:p-6 shadow-sm">@if($result)<div class="grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-3 gap-3 lg:gap-4">@foreach(['monthly_gross_cents'=>'Aylık brüt','gross_pay_cents'=>'Dönem brüt','employee_deductions_cents'=>'Çalışan kesintisi','net_pay_cents'=>'Net ücret','employer_contributions_cents'=>'İşveren katkısı','employer_total_cost_cents'=>'Toplam maliyet'] as $field=>$label)<div class="min-w-0 rounded-[8px] border border-slate-200 bg-slate-50/70 p-4"><p class="text-xs text-slate-500">{{ $label }}</p><p class="mt-1 truncate text-lg font-semibold text-slate-900">{{ number_format(($result[$field]??0)/100,2,',','.') }} ₺</p></div>@endforeach</div><div class="mt-4 rounded-lg border border-slate-200 overflow-hidden"><div class="grid grid-cols-2 gap-3 bg-slate-50/60 px-4 py-3 text-xs font-medium text-slate-500"><span>Hesap kalemi</span><span class="text-right">Tutar</span></div>@foreach(['employee_social_security_cents'=>'Çalışan SGK','employee_unemployment_cents'=>'Çalışan işsizlik','income_tax_cents'=>'Gelir vergisi','stamp_tax_cents'=>'Damga vergisi','period_tax_base_cents'=>'Dönem vergi matrahı'] as $field=>$label)<div class="grid grid-cols-2 gap-3 border-t border-slate-100 px-4 py-3 text-sm"><span class="text-slate-600">{{ $label }}</span><span class="text-right font-medium text-slate-900">{{ number_format(($result[$field]??0)/100,2,',','.') }} ₺</span></div>@endforeach</div>@else<div class="flex min-h-64 items-center justify-center text-sm text-slate-500">Hesaplama parametrelerini girip sonucu oluşturun.</div>@endif</section>
</div>
</div>
