<?php
namespace Tests\Feature\Hr;
use App\Models\LegalEntity; use App\Models\User; use App\Modules\Hr\Core\Services\TenantContext; use App\Modules\Hr\Personnel\Models\HrEmployee; use App\Modules\Hr\Training\Actions\CreateTrainingCourseAction; use App\Modules\Hr\Training\Actions\EnrollTrainingEmployeeAction; use App\Modules\Hr\Training\Actions\RecordTrainingResultAction; use App\Modules\Hr\Training\Actions\ScheduleTrainingSessionAction; use Illuminate\Support\Facades\DB; use Tests\TestCase;
class TrainingWorkflowTest extends TestCase { use RefreshHrDatabase; private User $user; private LegalEntity $tenant; private HrEmployee $employee; protected function setUp():void{parent::setUp();(new \Database\Seeders\Hr\HrPermissionSeeder)->run();$role=DB::table('roles')->where('slug','hr_admin')->value('id');$this->user=User::factory()->create(['role_id'=>$role]);$this->actingAs($this->user);$this->tenant=LegalEntity::create(['user_id'=>$this->user->id,'name'=>'Eğitim','tax_number'=>'5151515151','is_active'=>true]);app(TenantContext::class)->set($this->tenant);$this->employee=HrEmployee::withoutGlobalScope('tenant')->create(['legal_entity_id'=>$this->tenant->id,'user_id'=>$this->user->id,'employee_number'=>'TRN01','national_id_encrypted'=>'enc','national_id_hash'=>'training-employee','national_id_last_four'=>'0001','first_name'=>'Eğitim','last_name'=>'Çalışanı','status'=>'active']);}
public function test_passed_exam_issues_expiring_certificate_and_audits_result():void{$course=$this->course(['passing_score'=>70,'certificate_validity_months'=>12]);$session=$this->trainingSession($course,2);$enrollment=app(EnrollTrainingEmployeeAction::class)->execute($session,$this->employee);$result=app(RecordTrainingResultAction::class)->execute($enrollment,100,85);$this->assertSame('completed',$result->status);$this->assertTrue($result->passed);$this->assertNotNull($result->certificate);$this->assertSame(today()->addMonths(12)->toDateString(),$result->certificate->expires_on->toDateString());$this->assertDatabaseHas('activity_logs',['action'=>'training_result_recorded','user_id'=>$this->user->id]);}
public function test_failed_exam_does_not_issue_certificate():void{$course=$this->course(['passing_score'=>80]);$result=app(RecordTrainingResultAction::class)->execute(app(EnrollTrainingEmployeeAction::class)->execute($this->trainingSession($course,2),$this->employee),100,60);$this->assertSame('failed',$result->status);$this->assertFalse($result->passed);$this->assertNull($result->certificate);}
public function test_capacity_is_enforced_and_duplicate_enrollment_is_idempotent():void{$session=$this->trainingSession($this->course(),1);$action=app(EnrollTrainingEmployeeAction::class);$first=$action->execute($session,$this->employee);$this->assertTrue($first->is($action->execute($session,$this->employee)));$other=HrEmployee::withoutGlobalScope('tenant')->create(['legal_entity_id'=>$this->tenant->id,'employee_number'=>'TRN02','national_id_encrypted'=>'enc','national_id_hash'=>'training-other','national_id_last_four'=>'0002','first_name'=>'Diğer','last_name'=>'Çalışan','status'=>'active']);$this->expectException(\Symfony\Component\HttpKernel\Exception\HttpException::class);$action->execute($session,$other);}
public function test_cross_tenant_employee_cannot_be_enrolled():void{$session=$this->trainingSession($this->course(),2);$otherTenant=LegalEntity::create(['user_id'=>$this->user->id,'name'=>'Başka','tax_number'=>'5252525252','is_active'=>true]);$other=HrEmployee::withoutGlobalScope('tenant')->create(['legal_entity_id'=>$otherTenant->id,'employee_number'=>'OTH','national_id_encrypted'=>'enc','national_id_hash'=>'training-cross','national_id_last_four'=>'0003','first_name'=>'Başka','last_name'=>'Çalışan','status'=>'active']);$this->expectException(\Symfony\Component\HttpKernel\Exception\HttpException::class);app(EnrollTrainingEmployeeAction::class)->execute($session,$other);}
private function course(array $overrides=[]){return app(CreateTrainingCourseAction::class)->execute(array_merge(['code'=>'ISG','title'=>'İş Güvenliği','duration_minutes'=>60,'is_mandatory'=>true],$overrides));} private function trainingSession($course,?int $capacity){return app(ScheduleTrainingSessionAction::class)->execute($course,['starts_at'=>'2026-09-01 09:00','ends_at'=>'2026-09-01 11:00','capacity'=>$capacity]);}}
