<?php
namespace App\Modules\Hr\Payroll\Actions;
use App\Modules\Hr\Core\Services\HrAuditService; use App\Modules\Hr\Core\Services\TenantContext; use App\Modules\Hr\Overtime\Enums\OvertimeRequestStatus; use App\Modules\Hr\Overtime\Models\HrOvertimeRequest; use App\Modules\Hr\Payroll\Models\HrPayrollPeriod; use App\Modules\Hr\Payroll\Models\HrPayrollRecord; use App\Modules\Hr\Payroll\Models\HrPayrollRule; use App\Modules\Hr\Payroll\Services\PayrollRuleConfiguration; use App\Modules\Hr\Timesheet\Enums\TimesheetPeriodStatus; use App\Modules\Hr\Timesheet\Models\HrTimesheetPeriod; use Illuminate\Support\Facades\DB;
class PreparePayrollPeriodAction
{
 public function __construct(private HrAuditService $audit,private PayrollRuleConfiguration $configuration){}
 public function execute(HrTimesheetPeriod $timesheetPeriod):HrPayrollPeriod
 {
  abort_unless(auth()->user()?->hasHrPermission('hr.payroll.calculate'),403);$tenant=app(TenantContext::class)->getId();abort_unless($timesheetPeriod->legal_entity_id===$tenant,404);abort_unless($timesheetPeriod->status===TimesheetPeriodStatus::Closed,422,'Yalnız kapanmış puantaj bordro hazırlığına aktarılabilir.');
  $rows=$timesheetPeriod->timesheets()->with(['employee','latestCorrection'])->get()->groupBy('employee_id');$rules=HrPayrollRule::withoutGlobalScope('tenant')->where('legal_entity_id',$tenant)->whereIn('status',['approved','superseded'])->whereDate('effective_from','<=',$timesheetPeriod->ends_on)->where(fn($q)=>$q->whereNull('effective_until')->orWhereDate('effective_until','>=',$timesheetPeriod->starts_on))->orderBy('code')->orderByDesc('effective_from')->orderByDesc('version')->get()->unique('code')->map(fn($rule)=>['id'=>$rule->id,'code'=>$rule->code,'version'=>$rule->version,'configuration_hash'=>$rule->configuration_hash??hash('sha256',json_encode($rule->configuration,JSON_THROW_ON_ERROR|JSON_UNESCAPED_UNICODE))])->values()->all();$snapshots=[];
  foreach($rows as $employeeId=>$employeeRows){$approved=(int)HrOvertimeRequest::withoutGlobalScope('tenant')->where('legal_entity_id',$tenant)->where('employee_id',$employeeId)->where('status',OvertimeRequestStatus::Approved->value)->whereBetween('work_date',[$timesheetPeriod->starts_on,$timesheetPeriod->ends_on])->sum('approved_minutes');$snapshot=['timesheet_period_id'=>$timesheetPeriod->id,'employee_id'=>(int)$employeeId,'scheduled_minutes'=>$employeeRows->sum('scheduled_minutes'),'worked_minutes'=>$employeeRows->sum(fn($r)=>(int)$r->effective('worked_minutes')),'leave_minutes'=>$employeeRows->sum(fn($r)=>(int)$r->effective('leave_minutes')),'overtime_minutes'=>$employeeRows->sum(fn($r)=>(int)$r->effective('overtime_minutes')),'approved_overtime_minutes'=>$approved,'missing_minutes'=>$employeeRows->sum(fn($r)=>(int)$r->effective('missing_minutes')),'timesheet_revisions'=>$employeeRows->mapWithKeys(fn($r)=>[$r->id=>$r->latestCorrection?->revision_number??0])->all(),'rule_versions'=>$rules];$snapshots[]=$snapshot;}
  $sourceHash=$this->configuration->hash($snapshots);
  $period=DB::transaction(function()use($tenant,$timesheetPeriod,$snapshots,$sourceHash){$period=HrPayrollPeriod::withoutGlobalScope('tenant')->where('legal_entity_id',$tenant)->where('timesheet_period_id',$timesheetPeriod->id)->lockForUpdate()->first();abort_if($period&&$period->status==='approved',422,'Onaylanmış bordro hazırlık dönemi değiştirilemez.');if($period&&$period->source_hash===$sourceHash)return $period;$period??=HrPayrollPeriod::create(['legal_entity_id'=>$tenant,'timesheet_period_id'=>$timesheetPeriod->id,'name'=>$timesheetPeriod->name,'status'=>'draft']);$period->records()->delete();foreach($snapshots as $snapshot){$hash=$this->configuration->hash($snapshot);HrPayrollRecord::create(['legal_entity_id'=>$tenant,'payroll_period_id'=>$period->id,'employee_id'=>$snapshot['employee_id'],'scheduled_minutes'=>$snapshot['scheduled_minutes'],'worked_minutes'=>$snapshot['worked_minutes'],'leave_minutes'=>$snapshot['leave_minutes'],'overtime_minutes'=>$snapshot['overtime_minutes'],'approved_overtime_minutes'=>$snapshot['approved_overtime_minutes'],'missing_minutes'=>$snapshot['missing_minutes'],'source_snapshot'=>$snapshot,'source_hash'=>$hash]);}$period->update(['status'=>'prepared','source_hash'=>$sourceHash,'prepared_at'=>now(),'prepared_by'=>auth()->id(),'calculated_at'=>null,'calculated_by'=>null,'calculation_hash'=>null,'preflight_status'=>'pending','preflight_findings'=>null,'output_preflight_status'=>'pending','output_preflight_findings'=>null,'output_preflight_hash'=>null,'output_preflight_at'=>null,'output_preflight_by'=>null]);return $period;});$this->audit->log('payroll_period_prepared',$period,null,['source_hash'=>$sourceHash,'record_count'=>count($snapshots)]);return $period->fresh('records');
 }
}
