<div class="space-y-4 lg:space-y-6">
    <div class="flex flex-col sm:flex-row sm:items-start sm:justify-between gap-3">
        <div><h1 class="text-xl lg:text-2xl font-semibold text-slate-900">Masraf Kategorileri</h1><p class="mt-1 text-sm text-slate-500">Fiş zorunluluğu, varsayılan KDV ve onay limitlerini yönetin.</p></div>
        <a href="{{ route('hr.expenses') }}" class="w-full sm:w-auto px-4 py-3 sm:py-2 rounded-[6px] border border-slate-200 bg-white text-center text-sm text-slate-700">Masraflara dön</a>
    </div>
    @if(session('success'))<div class="rounded-[8px] border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-800">{{ session('success') }}</div>@endif
    <section class="rounded-[10px] border border-slate-200 bg-white shadow-sm overflow-hidden">
        <div class="border-b border-slate-200 p-4"><h2 class="text-sm font-semibold text-slate-900">{{ $editingId ? 'Kategoriyi düzenle' : 'Yeni kategori' }}</h2></div>
        <form wire:submit="save" class="grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-3 gap-3 lg:gap-4 bg-slate-50/60 p-4">
            <input wire:model.defer="code" class="text-base sm:text-sm rounded-[6px] border border-slate-200 bg-white px-3 py-3 sm:py-2" placeholder="Kod (SEYAHAT)">
            <input wire:model.defer="name" class="text-base sm:text-sm rounded-[6px] border border-slate-200 bg-white px-3 py-3 sm:py-2" placeholder="Kategori adı">
            <input type="number" step="0.01" wire:model.defer="defaultVatRate" class="text-base sm:text-sm rounded-[6px] border border-slate-200 bg-white px-3 py-3 sm:py-2" placeholder="Varsayılan KDV %">
            <input type="number" step="0.01" wire:model.defer="approvalLimit" class="text-base sm:text-sm rounded-[6px] border border-slate-200 bg-white px-3 py-3 sm:py-2" placeholder="Onay limiti (opsiyonel)">
            <label class="flex min-h-11 items-center gap-2 rounded-[6px] border border-slate-200 bg-white px-3 text-sm text-slate-700"><input type="checkbox" wire:model.defer="requiresReceipt" class="rounded border-slate-300"> Fiş/fatura zorunlu</label>
            <div class="flex flex-col sm:flex-row gap-2"><button class="w-full sm:w-auto px-4 py-3 sm:py-2 rounded-[6px] bg-slate-900 text-sm text-white">Kaydet</button>@if($editingId)<button type="button" wire:click="resetForm" class="w-full sm:w-auto px-4 py-3 sm:py-2 rounded-[6px] border border-slate-200 bg-white text-sm">Vazgeç</button>@endif</div>
            @if($errors->any())<p class="sm:col-span-2 xl:col-span-3 text-xs text-red-600">{{ $errors->first() }}</p>@endif
        </form>
    </section>
    <section class="rounded-[10px] border border-slate-200 bg-white shadow-sm overflow-hidden">
        <div class="hidden md:block overflow-x-auto rounded-lg"><table class="w-full table-fixed"><thead class="bg-slate-50/60 text-left text-xs uppercase text-slate-500"><tr><th class="px-4 py-3">Kod / kategori</th><th class="px-4 py-3">KDV</th><th class="px-4 py-3">Belge</th><th class="px-4 py-3">Limit</th><th class="px-4 py-3">Durum</th><th class="px-4 py-3 text-right">İşlem</th></tr></thead><tbody class="divide-y divide-slate-100">@forelse($categories as $category)<tr><td class="px-4 py-3 overflow-hidden"><p class="truncate text-sm font-medium text-slate-900">{{ $category->name }}</p><p class="text-xs font-mono text-slate-500">{{ $category->code }}</p></td><td class="px-4 py-3 text-sm text-slate-600">%{{ number_format($category->default_vat_rate, 2, ',', '.') }}</td><td class="px-4 py-3 text-sm text-slate-600">{{ $category->requires_receipt ? 'Zorunlu' : 'Opsiyonel' }}</td><td class="px-4 py-3 text-sm text-slate-600">{{ $category->approval_limit ? number_format($category->approval_limit, 2, ',', '.').' ₺' : '—' }}</td><td class="px-4 py-3"><span class="px-2 py-0.5 text-xs font-mono rounded {{ $category->is_active ? 'bg-emerald-50 text-emerald-700' : 'bg-slate-100 text-slate-600' }}">{{ $category->is_active ? 'Aktif' : 'Pasif' }}</span></td><td class="px-4 py-3 text-right"><button wire:click="edit({{ $category->id }})" class="px-3 py-2 text-xs text-slate-700">Düzenle</button><button wire:click="toggle({{ $category->id }})" class="px-3 py-2 text-xs text-slate-500">{{ $category->is_active ? 'Pasifleştir' : 'Aktifleştir' }}</button></td></tr>@empty<tr><td colspan="6" class="px-4 py-12 text-center text-sm text-slate-500">Kategori bulunamadı.</td></tr>@endforelse</tbody></table></div>
        <div class="md:hidden divide-y divide-slate-100">@forelse($categories as $category)<article class="p-4"><div class="flex justify-between gap-3"><div class="min-w-0"><p class="truncate text-sm font-medium text-slate-900">{{ $category->name }}</p><p class="mt-1 text-xs text-slate-500">{{ $category->code }} · KDV %{{ $category->default_vat_rate }} · {{ $category->requires_receipt ? 'Belge zorunlu' : 'Belge opsiyonel' }}</p></div><span class="px-2 py-0.5 text-xs font-mono rounded bg-slate-100">{{ $category->is_active ? 'Aktif' : 'Pasif' }}</span></div><div class="mt-3 grid grid-cols-2 gap-2"><button wire:click="edit({{ $category->id }})" class="w-full px-4 py-3 rounded-[6px] border border-slate-200 text-sm">Düzenle</button><button wire:click="toggle({{ $category->id }})" class="w-full px-4 py-3 rounded-[6px] border border-slate-200 text-sm">Durum değiştir</button></div></article>@empty<div class="p-8 text-center text-sm text-slate-500">Kategori bulunamadı.</div>@endforelse</div>
    </section>
</div>
