<div class="space-y-4 lg:space-y-6">
    <div class="flex flex-col sm:flex-row sm:items-start sm:justify-between gap-3"><div><h1 class="text-xl lg:text-2xl font-semibold text-slate-900">PDKS Cihazları</h1><p class="mt-1 text-sm text-slate-500">Turnike, QR, NFC, PIN ve API kaynaklarını yönetin.</p></div><a href="{{ route('hr.attendance') }}" class="w-full sm:w-auto px-4 py-3 sm:py-2 rounded-[6px] border border-slate-200 bg-white text-center text-sm font-medium text-slate-700">Olay defteri</a></div>
    @if(session('success'))<div class="rounded-[8px] border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-800">{{ session('success') }}</div>@endif
    @if($issuedSecret)<div class="rounded-[10px] border border-amber-200 bg-amber-50 p-4"><p class="text-sm font-semibold text-amber-900">Cihaz anahtarı yalnızca şimdi gösterilir</p><p class="mt-2 break-all rounded-[6px] border border-amber-200 bg-white px-3 py-2 font-mono text-sm text-slate-800">{{ $issuedSecret }}</p><p class="mt-2 text-xs text-amber-800">Anahtarı güvenli bir parola kasasına kaydedin.</p></div>@endif
    <div class="grid grid-cols-1 xl:grid-cols-3 gap-3 lg:gap-4">
        <form wire:submit="save" class="rounded-[10px] border border-slate-200 bg-white p-4 lg:p-6 shadow-sm space-y-3"><div><h2 class="text-sm font-semibold text-slate-900">{{ $editingId ? 'Cihazı düzenle' : 'Yeni cihaz' }}</h2><p class="mt-1 text-xs text-slate-500">Her cihaz kodu işletme içinde benzersizdir.</p></div><input wire:model.defer="code" class="w-full text-base sm:text-sm rounded-[6px] border border-slate-200 px-3 py-3 sm:py-2" placeholder="Cihaz kodu"><input wire:model.defer="name" class="w-full text-base sm:text-sm rounded-[6px] border border-slate-200 px-3 py-3 sm:py-2" placeholder="Cihaz adı"><select wire:model.defer="type" class="w-full text-base sm:text-sm rounded-[6px] border border-slate-200 px-3 py-3 sm:py-2"><option value="turnstile">Turnike</option><option value="qr">QR</option><option value="nfc">NFC</option><option value="pin">PIN</option><option value="api">API</option></select><input wire:model.defer="location" class="w-full text-base sm:text-sm rounded-[6px] border border-slate-200 px-3 py-3 sm:py-2" placeholder="Konum"><label class="flex items-center gap-2 text-sm text-slate-700"><input type="checkbox" wire:model.defer="isActive"> Aktif</label>@if($errors->any())<p class="text-xs text-red-600">{{ $errors->first() }}</p>@endif<div class="flex flex-col sm:flex-row gap-2"><button class="w-full sm:w-auto px-4 py-3 sm:py-2 rounded-[6px] bg-slate-900 text-sm font-medium text-white">Kaydet</button>@if($editingId)<button type="button" wire:click="resetForm" class="w-full sm:w-auto px-4 py-3 sm:py-2 rounded-[6px] border border-slate-200 text-sm text-slate-700">Vazgeç</button>@endif</div></form>
        <section class="xl:col-span-2 rounded-[10px] border border-slate-200 bg-white shadow-sm overflow-hidden"><div class="border-b border-slate-200 bg-slate-50/60 p-4"><h2 class="text-sm font-semibold text-slate-900">Kayıtlı cihazlar</h2></div><div class="divide-y divide-slate-100">@forelse($devices as $device)<article class="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3 p-4"><div class="min-w-0"><div class="flex items-center gap-2"><p class="truncate text-sm font-medium text-slate-900">{{ $device->name }}</p><span class="px-2 py-0.5 text-xs font-mono rounded {{ $device->is_active?'bg-emerald-50 text-emerald-700':'bg-slate-100 text-slate-500' }}">{{ $device->is_active?'Aktif':'Pasif' }}</span></div><p class="mt-1 text-xs text-slate-500">{{ $device->code }} · {{ strtoupper($device->type) }} · {{ $device->location ?: 'Konum yok' }}</p><p class="mt-1 text-xs text-slate-400">Son temas: {{ $device->last_seen_at?->format('d.m.Y H:i') ?? 'Henüz yok' }}</p></div><div class="flex gap-2"><button wire:click="edit({{ $device->id }})" class="flex-1 sm:flex-none px-3 py-2 rounded-[6px] border border-slate-200 text-xs text-slate-700">Düzenle</button><button wire:click="regenerateSecret({{ $device->id }})" wire:confirm="Eski cihaz anahtarı geçersiz olacak. Devam edilsin mi?" class="flex-1 sm:flex-none px-3 py-2 rounded-[6px] border border-amber-200 text-xs text-amber-700">Anahtarı yenile</button></div></article>@empty<div class="p-8 text-center text-sm text-slate-500">Kayıtlı cihaz yok.</div>@endforelse</div></section>
    </div>
</div>
