@php($labels=['missing_check_in'=>'Eksik giriş','missing_check_out'=>'Eksik çıkış','late_arrival'=>'Geç giriş','early_departure'=>'Erken çıkış','duplicate_check_in'=>'Tekrarlı giriş','check_out_without_check_in'=>'Girişsiz çıkış'])
<div class="space-y-4 lg:space-y-6">
    <div class="flex flex-col sm:flex-row sm:items-start sm:justify-between gap-3"><div><h1 class="text-xl lg:text-2xl font-semibold text-slate-900">PDKS Anomalileri</h1><p class="mt-1 text-sm text-slate-500">Vardiya planı ile gerçekleşen hareketler arasındaki farklar.</p></div><a href="{{ route('hr.attendance') }}" class="w-full sm:w-auto px-4 py-3 sm:py-2 rounded-[6px] border border-slate-200 bg-white text-center text-sm font-medium text-slate-700">Olay defteri</a></div>
    @if(session('success'))<div class="rounded-[8px] border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-800">{{ session('success') }}</div>@endif
    <div class="grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-3 gap-3 lg:gap-4"><div class="rounded-[8px] border border-slate-200 bg-slate-50/70 p-4"><p class="text-xs text-slate-500">Açık bulgu</p><p class="mt-1 text-2xl font-semibold text-slate-900">{{ $openCount }}</p></div><div class="rounded-[8px] border border-slate-200 bg-slate-50/70 p-4 sm:col-span-1 xl:col-span-2"><p class="text-xs text-slate-500">Kontrol yaklaşımı</p><p class="mt-1 text-sm text-slate-700">Yayımlanmış vardiyalar 5 dakikalık toleransla ve gece geçişleri dikkate alınarak değerlendirilir.</p></div></div>
    <section class="rounded-[10px] border border-slate-200 bg-white shadow-sm overflow-hidden">
        <div class="grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-4 gap-3 lg:gap-4 border-b border-slate-200 bg-slate-50/60 p-4 lg:p-6"><input wire:model.live.debounce.300ms="search" class="text-base sm:text-sm rounded-[6px] border border-slate-200 bg-white px-3 py-3 sm:py-2 xl:col-span-2" placeholder="Çalışan veya sicil ara"><select wire:model.live="statusFilter" class="text-base sm:text-sm rounded-[6px] border border-slate-200 bg-white px-3 py-3 sm:py-2"><option value="">Tüm durumlar</option><option value="open">Açık</option><option value="resolved">Çözüldü</option><option value="auto_resolved">Otomatik çözüldü</option></select><select wire:model.live="severityFilter" class="text-base sm:text-sm rounded-[6px] border border-slate-200 bg-white px-3 py-3 sm:py-2"><option value="">Tüm önem düzeyleri</option><option value="critical">Kritik</option><option value="warning">Uyarı</option><option value="info">Bilgi</option></select></div>
        <div class="hidden md:block overflow-x-auto rounded-lg"><table class="w-full table-fixed"><thead class="bg-slate-50/60 text-left text-xs uppercase text-slate-500"><tr><th class="px-4 py-3">Çalışan</th><th class="px-4 py-3">İş günü</th><th class="px-4 py-3">Bulgu</th><th class="px-4 py-3">Önem</th><th class="px-4 py-3">Durum</th><th class="px-4 py-3 text-right">İşlem</th></tr></thead><tbody class="divide-y divide-slate-100">@forelse($anomalies as $anomaly)<tr><td class="overflow-hidden text-ellipsis px-4 py-3 text-sm font-medium text-slate-900">{{ $anomaly->employee?->full_name }}</td><td class="px-4 py-3 text-sm text-slate-600">{{ $anomaly->work_date->format('d.m.Y') }}</td><td class="px-4 py-3 text-sm text-slate-700">{{ $labels[$anomaly->type] ?? $anomaly->type }}</td><td class="px-4 py-3"><span class="px-2 py-0.5 text-xs font-mono rounded {{ $anomaly->severity==='critical'?'bg-red-50 text-red-700':($anomaly->severity==='warning'?'bg-amber-50 text-amber-700':'bg-blue-50 text-blue-700') }}">{{ $anomaly->severity }}</span></td><td class="px-4 py-3 text-xs text-slate-600">{{ $anomaly->status }}</td><td class="px-4 py-3 text-right">@if($anomaly->status==='open' && auth()->user()?->hasHrPermission('hr.attendance.manage'))<button wire:click="startResolve({{ $anomaly->id }})" class="px-3 py-2 rounded-[6px] text-xs text-slate-700 hover:bg-slate-100">Çöz</button>@endif</td></tr>@empty<tr><td colspan="6" class="px-4 py-12 text-center text-sm text-slate-500">Anomali bulunamadı.</td></tr>@endforelse</tbody></table></div>
        <div class="md:hidden divide-y divide-slate-100">@forelse($anomalies as $anomaly)<article class="p-4"><div class="flex items-start justify-between gap-3"><div class="min-w-0"><p class="truncate text-sm font-medium text-slate-900">{{ $anomaly->employee?->full_name }}</p><p class="mt-1 text-xs text-slate-500">{{ $anomaly->work_date->format('d.m.Y') }} · {{ $labels[$anomaly->type] ?? $anomaly->type }}</p></div><span class="shrink-0 px-2 py-0.5 text-xs font-mono rounded bg-amber-50 text-amber-700">{{ $anomaly->severity }}</span></div>@if($anomaly->status==='open' && auth()->user()?->hasHrPermission('hr.attendance.manage'))<button wire:click="startResolve({{ $anomaly->id }})" class="mt-3 w-full px-4 py-3 rounded-[6px] border border-slate-200 text-sm text-slate-700">Çöz</button>@endif</article>@empty<div class="p-8 text-center text-sm text-slate-500">Anomali bulunamadı.</div>@endforelse</div><div class="border-t border-slate-200 p-4">{{ $anomalies->links() }}</div>
    </section>
    @if($resolvingId)<div class="fixed inset-0 z-50 flex items-end sm:items-center justify-center bg-slate-900/40 p-4"><form wire:submit="resolve" class="w-full max-w-md rounded-[10px] border border-slate-200 bg-white p-4 lg:p-6 shadow-md"><h2 class="text-lg font-semibold text-slate-900">Anomaliyi çöz</h2><p class="mt-1 text-sm text-slate-500">Yapılan kontrol veya düzeltmeyi açıklayın.</p><textarea wire:model.defer="resolutionNote" rows="3" class="mt-4 w-full text-base sm:text-sm rounded-[6px] border border-slate-200 px-3 py-3 sm:py-2" placeholder="Çözüm notu"></textarea>@error('resolutionNote')<p class="mt-1 text-xs text-red-600">{{ $message }}</p>@enderror<div class="mt-4 flex flex-col-reverse sm:flex-row sm:justify-end gap-2"><button type="button" wire:click="$set('resolvingId',null)" class="w-full sm:w-auto px-4 py-3 sm:py-2 rounded-[6px] border border-slate-200 text-sm">Vazgeç</button><button class="w-full sm:w-auto px-4 py-3 sm:py-2 rounded-[6px] bg-slate-900 text-sm text-white">Çözüldü olarak işaretle</button></div></form></div>@endif
</div>
