<div class="space-y-4 lg:space-y-6">
    <div class="flex flex-col sm:flex-row sm:items-start sm:justify-between gap-3">
        <div><h1 class="text-xl lg:text-2xl font-semibold text-slate-900">PDKS Olay Defteri</h1><p class="mt-1 text-sm text-slate-500">Tüm giriş, çıkış ve mola hareketlerinin değişmez kaynak kayıtları.</p></div>
        <div class="flex flex-col sm:flex-row gap-2"><a href="{{ route('hr.attendance.anomalies') }}" class="w-full sm:w-auto px-4 py-3 sm:py-2 rounded-[6px] border border-slate-200 bg-white text-center text-sm font-medium text-slate-700">Anomaliler</a>@if(auth()->user()?->hasHrPermission('hr.attendance.manage'))<a href="{{ route('hr.settings.attendance-devices') }}" class="w-full sm:w-auto px-4 py-3 sm:py-2 rounded-[6px] bg-slate-900 text-center text-sm font-medium text-white">Cihazlar</a>@endif</div>
    </div>

    @if(session('success'))<div class="rounded-[8px] border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-800">{{ session('success') }}</div>@endif

    @if(auth()->user()?->hasHrPermission('hr.attendance.manual_entry'))
        <section x-data="{open:false}" class="rounded-[10px] border border-slate-200 bg-white shadow-sm overflow-hidden">
            <button type="button" @click="open=!open" class="flex w-full items-center justify-between gap-3 p-4 text-left"><span><span class="block text-sm font-semibold text-slate-900">Manuel olay kaydı</span><span class="mt-1 block text-xs text-slate-500">Düzeltme gerekçesi audit kaydına eklenir.</span></span><span class="text-slate-400" x-text="open ? '−' : '+'"></span></button>
            <form x-show="open" x-cloak wire:submit="recordManual" class="grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-5 gap-3 lg:gap-4 border-t border-slate-200 bg-slate-50/60 p-4">
                <select wire:model.defer="employeeId" class="text-base sm:text-sm rounded-[6px] border border-slate-200 bg-white px-3 py-3 sm:py-2"><option value="">Çalışan seçin</option>@foreach($employees as $employee)<option value="{{ $employee->id }}">{{ $employee->full_name }} · {{ $employee->employee_number }}</option>@endforeach</select>
                <select wire:model.defer="manualEventType" class="text-base sm:text-sm rounded-[6px] border border-slate-200 bg-white px-3 py-3 sm:py-2">@foreach($eventTypes as $type)<option value="{{ $type->value }}">{{ $type->label() }}</option>@endforeach</select>
                <input type="datetime-local" wire:model.defer="manualOccurredAt" class="text-base sm:text-sm rounded-[6px] border border-slate-200 bg-white px-3 py-3 sm:py-2">
                <input wire:model.defer="manualReason" class="text-base sm:text-sm rounded-[6px] border border-slate-200 bg-white px-3 py-3 sm:py-2" placeholder="Zorunlu gerekçe">
                <button class="w-full sm:w-auto px-4 py-3 sm:py-2 rounded-[6px] bg-slate-900 text-sm font-medium text-white" wire:loading.attr="disabled" wire:target="recordManual">Kaydet</button>
                @if($errors->any())<p class="sm:col-span-2 xl:col-span-5 text-xs text-red-600">{{ $errors->first() }}</p>@endif
            </form>
        </section>
    @endif

    <section class="rounded-[10px] border border-slate-200 bg-white shadow-sm overflow-hidden">
        <div class="border-b border-slate-200 bg-slate-50/60 p-4 lg:p-6">
            <div class="mb-3 flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3"><div><h2 class="text-sm font-semibold text-slate-900">Hareket akışı</h2><p class="mt-1 text-xs text-slate-500">{{ $events->total() }} kayıt · {{ $dateFrom }} / {{ $dateTo }}</p></div><div x-data="{open:false}" class="relative"><button @click="open=!open" type="button" class="w-full sm:w-auto px-4 py-3 sm:py-2 rounded-[6px] border border-slate-200 bg-white text-sm text-slate-700">Kolonlar · {{ count($visibleColumns) }}</button><div x-show="open" @click.outside="open=false" x-cloak class="absolute right-0 z-20 mt-2 w-52 rounded-[8px] border border-slate-200 bg-white p-2 shadow-md">@foreach(['employee'=>'Çalışan','event_type'=>'Hareket','occurred_at'=>'Tarih / saat','source'=>'Kaynak','device'=>'Cihaz','manual'=>'Kayıt türü'] as $key=>$label)<label class="flex items-center gap-2 rounded px-2 py-2 text-sm text-slate-700"><input type="checkbox" wire:click="toggleColumn('{{ $key }}')" @checked(in_array($key,$visibleColumns,true))>{{ $label }}</label>@endforeach</div></div></div>
            <div class="grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-6 gap-3 lg:gap-4">
                <input wire:model.live.debounce.300ms="search" class="text-base sm:text-sm rounded-[6px] border border-slate-200 bg-white px-3 py-3 sm:py-2 xl:col-span-2" placeholder="Çalışan veya sicil ara">
                <select wire:model.live="typeFilter" class="text-base sm:text-sm rounded-[6px] border border-slate-200 bg-white px-3 py-3 sm:py-2"><option value="">Tüm hareketler</option>@foreach($eventTypes as $type)<option value="{{ $type->value }}">{{ $type->label() }}</option>@endforeach</select>
                <select wire:model.live="sourceFilter" class="text-base sm:text-sm rounded-[6px] border border-slate-200 bg-white px-3 py-3 sm:py-2"><option value="">Tüm kaynaklar</option>@foreach(['web'=>'Web','turnstile'=>'Turnike','qr'=>'QR','pin'=>'PIN','nfc'=>'NFC','api'=>'API','manual'=>'Manuel'] as $key=>$label)<option value="{{ $key }}">{{ $label }}</option>@endforeach</select>
                <input type="date" wire:model.live="dateFrom" class="text-base sm:text-sm rounded-[6px] border border-slate-200 bg-white px-3 py-3 sm:py-2">
                <div class="flex gap-2"><input type="date" wire:model.live="dateTo" class="min-w-0 flex-1 text-base sm:text-sm rounded-[6px] border border-slate-200 bg-white px-3 py-3 sm:py-2"><button wire:click="resetFilters" class="px-3 py-3 sm:py-2 rounded-[6px] border border-slate-200 bg-white text-sm text-slate-600">Temizle</button></div>
            </div>
        </div>

        <div class="hidden md:block overflow-x-auto rounded-lg" x-data="columnResize()">
            <table class="w-full table-fixed"><thead class="bg-slate-50/60 text-left text-xs uppercase text-slate-500"><tr>@if(in_array('employee',$visibleColumns,true))<th class="px-4 py-3">Çalışan</th>@endif @if(in_array('event_type',$visibleColumns,true))<th wire:click="sortTable('event_type')" class="cursor-pointer px-4 py-3">Hareket</th>@endif @if(in_array('occurred_at',$visibleColumns,true))<th wire:click="sortTable('occurred_at')" class="cursor-pointer px-4 py-3">Tarih / saat</th>@endif @if(in_array('source',$visibleColumns,true))<th wire:click="sortTable('source')" class="cursor-pointer px-4 py-3">Kaynak</th>@endif @if(in_array('device',$visibleColumns,true))<th class="px-4 py-3">Cihaz</th>@endif @if(in_array('manual',$visibleColumns,true))<th wire:click="sortTable('is_manual')" class="cursor-pointer px-4 py-3">Kayıt türü</th>@endif</tr></thead>
                <tbody class="divide-y divide-slate-100">@forelse($events as $event)<tr class="hover:bg-slate-50/60">@if(in_array('employee',$visibleColumns,true))<td class="overflow-hidden text-ellipsis px-4 py-3 text-sm font-medium text-slate-900">{{ $event->employee?->full_name }} <span class="text-slate-400">{{ $event->employee?->employee_number }}</span></td>@endif @if(in_array('event_type',$visibleColumns,true))<td class="px-4 py-3"><span class="px-2 py-0.5 text-xs font-mono rounded {{ $event->event_type->value === 'check_in' ? 'bg-emerald-50 text-emerald-700' : ($event->event_type->value === 'check_out' ? 'bg-slate-100 text-slate-700' : 'bg-blue-50 text-blue-700') }}">{{ $event->event_type->label() }}</span></td>@endif @if(in_array('occurred_at',$visibleColumns,true))<td class="px-4 py-3 text-sm text-slate-600">{{ $event->occurred_at->format('d.m.Y H:i:s') }}</td>@endif @if(in_array('source',$visibleColumns,true))<td class="px-4 py-3 text-sm uppercase text-slate-600">{{ $event->source }}</td>@endif @if(in_array('device',$visibleColumns,true))<td class="overflow-hidden text-ellipsis px-4 py-3 text-sm text-slate-600">{{ $event->device?->name ?? '—' }}</td>@endif @if(in_array('manual',$visibleColumns,true))<td class="px-4 py-3 text-xs text-slate-600">{{ $event->is_manual ? 'Manuel' : 'Otomatik' }}</td>@endif</tr>@empty<tr><td colspan="{{ count($visibleColumns) }}" class="px-4 py-12 text-center text-sm text-slate-500">Filtrelerle eşleşen olay bulunamadı.</td></tr>@endforelse</tbody></table>
        </div>
        <div class="md:hidden divide-y divide-slate-100">@forelse($events as $event)<article class="p-4"><div class="flex items-start justify-between gap-3"><div class="min-w-0"><p class="truncate text-sm font-medium text-slate-900">{{ $event->employee?->full_name }}</p><p class="mt-1 text-xs text-slate-500">{{ $event->occurred_at->format('d.m.Y H:i:s') }} · {{ strtoupper($event->source) }}</p></div><span class="shrink-0 px-2 py-0.5 text-xs font-mono rounded bg-slate-100 text-slate-700">{{ $event->event_type->label() }}</span></div>@if($event->is_manual)<p class="mt-3 text-xs text-amber-700">Manuel · {{ $event->manual_reason }}</p>@endif</article>@empty<div class="p-8 text-center text-sm text-slate-500">Olay bulunamadı.</div>@endforelse</div>
        <div class="border-t border-slate-200 p-4">{{ $events->links() }}</div>
    </section>
</div>
