<div class="max-w-3xl space-y-4 lg:space-y-6">
    <div><a href="{{ route('hr.settings.leave-types') }}" class="text-sm text-slate-500">← İzin türlerine dön</a><h1 class="mt-2 text-xl lg:text-2xl font-semibold text-slate-900">{{ $isEdit ? 'İzin Türünü Düzenle' : 'Yeni İzin Türü' }}</h1></div>
    <form wire:submit="save" class="rounded-[10px] border border-slate-200 bg-white shadow-sm p-4 lg:p-6 space-y-5">
        <div class="grid grid-cols-1 sm:grid-cols-2 gap-3 lg:gap-4"><label class="block"><span class="text-sm font-medium text-slate-700">Ad</span><input wire:model.defer="name" class="mt-1 w-full text-base sm:text-sm rounded-[6px] border border-slate-200 px-3 py-3 sm:py-2">@error('name')<span class="text-xs text-red-600">{{ $message }}</span>@enderror</label><label class="block"><span class="text-sm font-medium text-slate-700">Kod</span><input wire:model.defer="code" class="mt-1 w-full text-base sm:text-sm rounded-[6px] border border-slate-200 px-3 py-3 sm:py-2 uppercase">@error('code')<span class="text-xs text-red-600">{{ $message }}</span>@enderror</label></div>
        <label class="block max-w-sm"><span class="text-sm font-medium text-slate-700">Birim</span><select wire:model.defer="unit" class="mt-1 w-full text-base sm:text-sm rounded-[6px] border border-slate-200 px-3 py-3 sm:py-2"><option value="day">Gün</option><option value="hour">Saat</option></select></label>
        <div class="grid grid-cols-1 sm:grid-cols-2 gap-3"><label class="flex items-center gap-3 rounded-[8px] border border-slate-200 bg-slate-50/60 p-3 text-sm"><input type="checkbox" wire:model.defer="is_paid"> Ücretli izin</label><label class="flex items-center gap-3 rounded-[8px] border border-slate-200 bg-slate-50/60 p-3 text-sm"><input type="checkbox" wire:model.defer="requires_document"> Belge zorunlu</label><label class="flex items-center gap-3 rounded-[8px] border border-slate-200 bg-slate-50/60 p-3 text-sm"><input type="checkbox" wire:model.defer="allows_negative_balance"> Eksi bakiyeye izin ver</label><label class="flex items-center gap-3 rounded-[8px] border border-slate-200 bg-slate-50/60 p-3 text-sm"><input type="checkbox" wire:model.defer="is_active"> Aktif</label></div>
        <div class="flex flex-col sm:flex-row gap-3 pt-2"><button class="w-full sm:w-auto px-4 py-3 sm:py-2 rounded-[6px] bg-slate-900 text-white text-sm font-medium" wire:loading.attr="disabled">Kaydet</button><a href="{{ route('hr.settings.leave-types') }}" class="w-full sm:w-auto px-4 py-3 sm:py-2 rounded-[6px] border border-slate-200 text-center text-sm text-slate-700">İptal</a></div>
    </form>
</div>
