<div class="max-w-3xl space-y-4 lg:space-y-6">
    <div>
        <a href="{{ route('hr.leaves') }}" class="text-sm text-slate-500">← İzin taleplerine dön</a>
        <h1 class="mt-2 text-xl lg:text-2xl font-semibold text-slate-900">Yeni İzin Talebi</h1>
    </div>
    <form wire:submit="save" class="rounded-[10px] border border-slate-200 bg-white shadow-sm p-4 lg:p-6 space-y-5">
        <div class="grid grid-cols-1 sm:grid-cols-2 gap-3 lg:gap-4">
            <label><span class="text-sm font-medium text-slate-700">Çalışan</span><select wire:model.live="employee_id" class="mt-1 w-full text-base sm:text-sm rounded-[6px] border border-slate-200 px-3 py-3 sm:py-2"><option value="">Seçin</option>@foreach($employees as $employee)<option value="{{ $employee->id }}">{{ $employee->full_name }} · {{ $employee->employee_number }}</option>@endforeach</select>@error('employee_id')<span class="text-xs text-red-600">{{ $message }}</span>@enderror</label>
            <label><span class="text-sm font-medium text-slate-700">İzin türü</span><select wire:model.defer="leave_type_id" class="mt-1 w-full text-base sm:text-sm rounded-[6px] border border-slate-200 px-3 py-3 sm:py-2"><option value="">Seçin</option>@foreach($leaveTypes as $type)<option value="{{ $type->id }}">{{ $type->name }} ({{ $type->unit->label() }})</option>@endforeach</select>@error('leave_type_id')<span class="text-xs text-red-600">{{ $message }}</span>@enderror</label>
            <label><span class="text-sm font-medium text-slate-700">Başlangıç</span><input type="date" wire:model.defer="start_date" class="mt-1 w-full text-base sm:text-sm rounded-[6px] border border-slate-200 px-3 py-3 sm:py-2">@error('start_date')<span class="text-xs text-red-600">{{ $message }}</span>@enderror</label>
            <label><span class="text-sm font-medium text-slate-700">Bitiş</span><input type="date" wire:model.defer="end_date" class="mt-1 w-full text-base sm:text-sm rounded-[6px] border border-slate-200 px-3 py-3 sm:py-2">@error('end_date')<span class="text-xs text-red-600">{{ $message }}</span>@enderror</label>
        </div>
        <label class="block"><span class="text-sm font-medium text-slate-700">Belge <span class="text-slate-400">(izin türü gerektiriyorsa zorunlu)</span></span><select wire:model.defer="document_id" class="mt-1 w-full text-base sm:text-sm rounded-[6px] border border-slate-200 px-3 py-3 sm:py-2"><option value="">Belge seçmeyin</option>@foreach($documents as $document)<option value="{{ $document->id }}">{{ $document->documentType?->name ?? 'Belge' }} · {{ $document->created_at->format('d.m.Y') }}</option>@endforeach</select></label>
        <div class="grid grid-cols-1 sm:grid-cols-2 gap-3 lg:gap-4"><label><span class="text-sm font-medium text-slate-700">Başlangıç saati <span class="text-slate-400">(saatlik)</span></span><input type="time" wire:model.defer="start_time" class="mt-1 w-full text-base sm:text-sm rounded-[6px] border border-slate-200 px-3 py-3 sm:py-2"></label><label><span class="text-sm font-medium text-slate-700">Bitiş saati <span class="text-slate-400">(saatlik)</span></span><input type="time" wire:model.defer="end_time" class="mt-1 w-full text-base sm:text-sm rounded-[6px] border border-slate-200 px-3 py-3 sm:py-2"></label></div>
        <label class="block"><span class="text-sm font-medium text-slate-700">Gerekçe</span><textarea wire:model.defer="reason" rows="3" class="mt-1 w-full text-base sm:text-sm rounded-[6px] border border-slate-200 px-3 py-3 sm:py-2"></textarea></label>
        <div class="flex flex-col sm:flex-row gap-3"><button class="w-full sm:w-auto px-4 py-3 sm:py-2 rounded-[6px] bg-slate-900 text-white text-sm font-medium" wire:loading.attr="disabled">Talep Oluştur</button><a href="{{ route('hr.leaves') }}" class="w-full sm:w-auto px-4 py-3 sm:py-2 rounded-[6px] border border-slate-200 text-center text-sm text-slate-700">İptal</a></div>
    </form>
</div>
