<div class="max-w-4xl space-y-4 lg:space-y-6"><div><a href="{{ route('hr.settings.leave-policies') }}" class="text-sm text-slate-500">← Politikalara dön</a><h1 class="mt-2 text-xl lg:text-2xl font-semibold text-slate-900">{{ $isEdit ? 'İzin Politikasını Düzenle' : 'Yeni İzin Politikası' }}</h1></div><form wire:submit="save" class="rounded-[10px] border border-slate-200 bg-white shadow-sm p-4 lg:p-6 space-y-5">
    <div class="grid grid-cols-1 sm:grid-cols-2 gap-3 lg:gap-4"><label><span class="text-sm font-medium text-slate-700">İzin türü</span><select wire:model.defer="leave_type_id" class="mt-1 w-full text-base sm:text-sm rounded-[6px] border border-slate-200 px-3 py-3 sm:py-2"><option value="">Seçin</option>@foreach($leaveTypes as $type)<option value="{{ $type->id }}">{{ $type->name }}</option>@endforeach</select>@error('leave_type_id')<span class="text-xs text-red-600">{{ $message }}</span>@enderror</label><label><span class="text-sm font-medium text-slate-700">Kapsam</span><select wire:model.live="scope" class="mt-1 w-full text-base sm:text-sm rounded-[6px] border border-slate-200 px-3 py-3 sm:py-2"><option value="company">Şirket geneli</option><option value="branch">Şube</option><option value="department">Departman</option><option value="position">Pozisyon</option><option value="employment_type">İstihdam tipi</option></select></label></div>
    @if($scope === 'branch')<label><span class="text-sm font-medium text-slate-700">Şube</span><select wire:model.defer="branch_id" class="mt-1 w-full text-base sm:text-sm rounded-[6px] border border-slate-200 px-3 py-3 sm:py-2"><option value="">Seçin</option>@foreach($branches as $item)<option value="{{ $item->id }}">{{ $item->name }}</option>@endforeach</select></label>@endif
    @if($scope === 'department')<label><span class="text-sm font-medium text-slate-700">Departman</span><select wire:model.defer="department_id" class="mt-1 w-full text-base sm:text-sm rounded-[6px] border border-slate-200 px-3 py-3 sm:py-2"><option value="">Seçin</option>@foreach($departments as $item)<option value="{{ $item->id }}">{{ $item->name }}</option>@endforeach</select></label>@endif
    @if($scope === 'position')<label><span class="text-sm font-medium text-slate-700">Pozisyon</span><select wire:model.defer="position_id" class="mt-1 w-full text-base sm:text-sm rounded-[6px] border border-slate-200 px-3 py-3 sm:py-2"><option value="">Seçin</option>@foreach($positions as $item)<option value="{{ $item->id }}">{{ $item->title }}</option>@endforeach</select></label>@endif
    @if($scope === 'employment_type')<label><span class="text-sm font-medium text-slate-700">İstihdam tipi</span><select wire:model.defer="employment_type" class="mt-1 w-full text-base sm:text-sm rounded-[6px] border border-slate-200 px-3 py-3 sm:py-2"><option value="">Seçin</option><option value="full_time">Tam zamanlı</option><option value="part_time">Yarı zamanlı</option><option value="contract">Sözleşmeli</option><option value="intern">Stajyer</option><option value="temporary">Geçici</option></select></label>@endif
    <div class="grid grid-cols-1 sm:grid-cols-2 gap-3 lg:gap-4"><label><span class="text-sm font-medium text-slate-700">Yıllık hak ediş</span><input type="number" step="0.01" min="0" wire:model.defer="annual_entitlement" class="mt-1 w-full text-base sm:text-sm rounded-[6px] border border-slate-200 px-3 py-3 sm:py-2"></label><label><span class="text-sm font-medium text-slate-700">Maks. devir</span><input type="number" step="0.01" min="0" wire:model.defer="max_carryover" class="mt-1 w-full text-base sm:text-sm rounded-[6px] border border-slate-200 px-3 py-3 sm:py-2"></label><label><span class="text-sm font-medium text-slate-700">Başlangıç</span><input type="date" wire:model.defer="effective_from" class="mt-1 w-full text-base sm:text-sm rounded-[6px] border border-slate-200 px-3 py-3 sm:py-2"></label><label><span class="text-sm font-medium text-slate-700">Bitiş</span><input type="date" wire:model.defer="effective_until" class="mt-1 w-full text-base sm:text-sm rounded-[6px] border border-slate-200 px-3 py-3 sm:py-2"></label></div>
    <div class="grid grid-cols-1 sm:grid-cols-3 gap-3"><label class="flex items-center gap-3 rounded-[8px] border border-slate-200 bg-slate-50/60 p-3 text-sm"><input type="checkbox" wire:model.defer="allows_negative_balance"> Eksi bakiye</label><label class="flex items-center gap-3 rounded-[8px] border border-slate-200 bg-slate-50/60 p-3 text-sm"><input type="checkbox" wire:model.defer="requires_hr_approval"> İK onayı</label><label class="flex items-center gap-3 rounded-[8px] border border-slate-200 bg-slate-50/60 p-3 text-sm"><input type="checkbox" wire:model.defer="is_active"> Aktif</label></div>
    <div class="flex flex-col sm:flex-row gap-3"><button class="w-full sm:w-auto px-4 py-3 sm:py-2 rounded-[6px] bg-slate-900 text-white text-sm font-medium">Kaydet</button><a href="{{ route('hr.settings.leave-policies') }}" class="w-full sm:w-auto px-4 py-3 sm:py-2 rounded-[6px] border border-slate-200 text-center text-sm text-slate-700">İptal</a></div>
</form></div>
