<div class="space-y-4 lg:space-y-6">
    <div class="flex flex-col sm:flex-row sm:items-start sm:justify-between gap-3">
        <div><h1 class="text-xl lg:text-2xl font-semibold text-slate-900">İzin Türleri</h1><p class="text-sm text-slate-500 mt-1">{{ $types->total() }} tanım · kullanılan türler silinmez, pasife alınır.</p></div>
        @if(auth()->user()?->hasHrPermission('hr.leaves.manage_type'))<a href="{{ route('hr.settings.leave-types.create') }}" class="w-full sm:w-auto px-4 py-3 sm:py-2 rounded-[6px] bg-slate-900 text-white text-sm font-medium text-center">+ Yeni İzin Türü</a>@endif
    </div>
    @if(session('success'))<div class="rounded-[8px] border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-800">{{ session('success') }}</div>@endif
    <section class="rounded-[10px] border border-slate-200 bg-white shadow-sm overflow-hidden">
        <div class="p-4 lg:p-6 border-b border-slate-200 bg-slate-50/60">
            <div class="grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-4 gap-3 lg:gap-4">
                <input wire:model.live.debounce.300ms="search" class="text-base sm:text-sm rounded-[6px] border border-slate-200 bg-white px-3 py-3 sm:py-2" placeholder="Ad veya kod ara">
                <select wire:model.live="unitFilter" class="text-base sm:text-sm rounded-[6px] border border-slate-200 bg-white px-3 py-3 sm:py-2"><option value="">Tüm birimler</option><option value="day">Gün</option><option value="hour">Saat</option></select>
                <select wire:model.live="statusFilter" class="text-base sm:text-sm rounded-[6px] border border-slate-200 bg-white px-3 py-3 sm:py-2"><option value="">Tüm durumlar</option><option value="active">Aktif</option><option value="inactive">Pasif</option></select>
                <button wire:click="resetFilters" class="w-full sm:w-auto px-4 py-3 sm:py-2 rounded-[6px] border border-slate-200 bg-white text-sm text-slate-700">Temizle</button>
            </div>
        </div>
        <div class="hidden md:block overflow-x-auto"><table class="w-full table-fixed"><thead class="bg-slate-50/60 text-left text-xs uppercase tracking-wide text-slate-500"><tr><th class="px-4 py-3 w-28">Kod</th><th class="px-4 py-3">İzin türü</th><th class="px-4 py-3 w-28">Birim</th><th class="px-4 py-3 w-36">Ücret</th><th class="px-4 py-3 w-28">Durum</th><th class="px-4 py-3 w-40 text-right">İşlemler</th></tr></thead><tbody class="divide-y divide-slate-100">
            @forelse($types as $type)<tr class="hover:bg-slate-50/60"><td class="px-4 py-3 text-sm font-mono text-slate-700 truncate">{{ $type->code }}</td><td class="px-4 py-3 text-sm font-medium text-slate-900 truncate">{{ $type->name }}</td><td class="px-4 py-3 text-sm text-slate-600">{{ $type->unit->label() }}</td><td class="px-4 py-3 text-sm text-slate-600">{{ $type->is_paid ? 'Ücretli' : 'Ücretsiz' }}</td><td class="px-4 py-3"><span class="px-2 py-0.5 text-xs font-mono rounded {{ $type->is_active ? 'bg-emerald-50 text-emerald-700' : 'bg-slate-100 text-slate-600' }}">{{ $type->is_active ? 'Aktif' : 'Pasif' }}</span></td><td class="px-4 py-3 text-right whitespace-nowrap"><a href="{{ route('hr.settings.leave-types.edit', $type->id) }}" class="text-sm text-slate-700">Düzenle</a>@if(auth()->user()?->hasHrPermission('hr.leaves.manage_type'))<button wire:click="toggleActive({{ $type->id }})" class="ml-3 text-sm {{ $type->is_active ? 'text-amber-700' : 'text-emerald-700' }}">{{ $type->is_active ? 'Pasifleştir' : 'Aktifleştir' }}</button>@endif</td></tr>
            @empty<tr><td colspan="6" class="px-4 py-10 text-center text-sm text-slate-500">Filtreye uygun izin türü bulunmuyor.</td></tr>@endforelse
        </tbody></table></div>
        <div class="md:hidden divide-y divide-slate-100">@forelse($types as $type)<article class="p-4 min-w-0"><div class="flex items-start justify-between gap-3"><div class="min-w-0"><p class="text-sm font-medium text-slate-900 truncate">{{ $type->name }}</p><p class="text-xs font-mono text-slate-500 mt-1">{{ $type->code }} · {{ $type->unit->label() }} · {{ $type->is_paid ? 'Ücretli' : 'Ücretsiz' }}</p></div><span class="px-2 py-0.5 text-xs font-mono rounded {{ $type->is_active ? 'bg-emerald-50 text-emerald-700' : 'bg-slate-100 text-slate-600' }}">{{ $type->is_active ? 'Aktif' : 'Pasif' }}</span></div><div class="mt-3 flex gap-3"><a href="{{ route('hr.settings.leave-types.edit', $type->id) }}" class="text-sm text-slate-700">Düzenle</a><button wire:click="toggleActive({{ $type->id }})" class="text-sm text-amber-700">{{ $type->is_active ? 'Pasifleştir' : 'Aktifleştir' }}</button></div></article>@empty<div class="p-8 text-center text-sm text-slate-500">İzin türü bulunmuyor.</div>@endforelse</div>
        <div class="p-4 border-t border-slate-200">{{ $types->links() }}</div>
    </section>
</div>
