<?php
namespace App\Modules\Hr\Payroll\Livewire;
use App\Modules\Hr\Core\Services\HrAuditService; use App\Modules\Hr\Core\Services\TenantContext; use App\Modules\Hr\Payroll\Models\HrPayrollRule; use Livewire\Component;
class PayrollRuleManager extends Component
{
 public string $code='';public string $name='';public int $version=1;public string $configuration='{}';public string $effectiveFrom='';public ?string $effectiveUntil=null;
 public function mount():void{$this->effectiveFrom=now()->startOfMonth()->toDateString();}
 public function save(HrAuditService $audit):void{abort_unless(auth()->user()?->hasHrPermission('hr.payroll.manage_rules'),403);$this->validate(['code'=>'required|string|max:60','name'=>'required|string|max:160','version'=>'required|integer|min:1','configuration'=>'required|json','effectiveFrom'=>'required|date','effectiveUntil'=>'nullable|date|after_or_equal:effectiveFrom']);$tenant=app(TenantContext::class)->getId();$code=strtoupper(trim($this->code));abort_if(HrPayrollRule::withoutGlobalScope('tenant')->where('legal_entity_id',$tenant)->where('code',$code)->where('version',$this->version)->exists(),422,'Bu kural sürümü zaten var.');$rule=HrPayrollRule::create(['legal_entity_id'=>$tenant,'code'=>$code,'name'=>trim($this->name),'version'=>$this->version,'configuration'=>json_decode($this->configuration,true,512,JSON_THROW_ON_ERROR),'effective_from'=>$this->effectiveFrom,'effective_until'=>$this->effectiveUntil?:null,'is_active'=>true,'created_by'=>auth()->id()]);$audit->log('payroll_rule_version_created',$rule,null,['code'=>$code,'version'=>$this->version]);$this->reset(['code','name','configuration','effectiveUntil']);$this->configuration='{}';$this->version=1;session()->flash('success','Yeni kural sürümü kaydedildi.');}
 public function render(){return view('livewire.hr.payroll.payroll-rule-manager',['rules'=>HrPayrollRule::withoutGlobalScope('tenant')->where('legal_entity_id',app(TenantContext::class)->getId())->orderBy('code')->orderByDesc('version')->get()])->layout('layouts.app');}
}
