<?php
namespace App\Modules\Hr\Payroll\Livewire;
use App\Modules\Hr\Core\Services\HrAuditService; use App\Modules\Hr\Core\Services\TenantContext; use App\Modules\Hr\Payroll\Actions\ApprovePayrollRuleAction; use App\Modules\Hr\Payroll\Models\HrPayrollRule; use App\Modules\Hr\Payroll\Services\PayrollRuleConfiguration; use Livewire\Component;
class PayrollRuleManager extends Component
{
 public string $code='';public string $name='';public int $version=1;public string $configuration='{}';public string $effectiveFrom='';public ?string $effectiveUntil=null;
 public function mount():void{$this->effectiveFrom=now()->startOfMonth()->toDateString();}
 public function save(HrAuditService $audit,PayrollRuleConfiguration $configurationService):void{abort_unless(auth()->user()?->hasHrPermission('hr.payroll.manage_rules'),403);$this->validate(['code'=>'required|string|max:60','name'=>'required|string|max:160','version'=>'required|integer|min:1','configuration'=>'required|json','effectiveFrom'=>'required|date','effectiveUntil'=>'nullable|date|after_or_equal:effectiveFrom']);$tenant=app(TenantContext::class)->getId();$code=strtoupper(trim($this->code));abort_if(HrPayrollRule::withoutGlobalScope('tenant')->where('legal_entity_id',$tenant)->where('code',$code)->where('version',$this->version)->exists(),422,'Bu kural sürümü zaten var.');$configuration=json_decode($this->configuration,true,512,JSON_THROW_ON_ERROR);if($code===PayrollRuleConfiguration::CODE)$configurationService->validate($configuration);$rule=HrPayrollRule::create(['legal_entity_id'=>$tenant,'code'=>$code,'name'=>trim($this->name),'version'=>$this->version,'configuration'=>$configuration,'configuration_hash'=>$configurationService->hash($configuration),'effective_from'=>$this->effectiveFrom,'effective_until'=>$this->effectiveUntil?:null,'is_active'=>false,'status'=>'pending_approval','created_by'=>auth()->id()]);$audit->log('payroll_rule_version_created',$rule,null,['code'=>$code,'version'=>$this->version,'configuration_hash'=>$rule->configuration_hash]);$this->reset(['code','name','configuration','effectiveUntil']);$this->configuration='{}';$this->version=1;session()->flash('success','Yeni kural sürümü onaya gönderildi.');}
 public function approve(int $id,ApprovePayrollRuleAction $action):void{$rule=HrPayrollRule::withoutGlobalScope('tenant')->where('legal_entity_id',app(TenantContext::class)->getId())->findOrFail($id);$action->execute($rule);session()->flash('success','Kural sürümü onaylandı ve yürürlüğe hazırlandı.');}
 public function render(){return view('livewire.hr.payroll.payroll-rule-manager',['rules'=>HrPayrollRule::withoutGlobalScope('tenant')->where('legal_entity_id',app(TenantContext::class)->getId())->orderBy('code')->orderByDesc('version')->get()])->layout('layouts.app');}
}
