<?php

return [
    'manual_sync' => [
        'debounce_seconds' => (int) env('MARKETPLACE_MANUAL_SYNC_DEBOUNCE_SECONDS', 30),
        'active_run_block_seconds' => (int) env('MARKETPLACE_MANUAL_SYNC_ACTIVE_RUN_BLOCK_SECONDS', 900),
        'active_statuses' => ['queued', 'processing', 'retrying'],
        'inline_on_local' => (bool) env('MARKETPLACE_MANUAL_SYNC_INLINE_ON_LOCAL', true),
    ],

    'notifications' => [
        'read_retention_hours' => (int) env('MARKETPLACE_NOTIFICATION_READ_RETENTION_HOURS', 24),
        'unread_retention_days' => (int) env('MARKETPLACE_NOTIFICATION_UNREAD_RETENTION_DAYS', 7),
        'failure_cooldown_seconds' => (int) env('MARKETPLACE_NOTIFICATION_FAILURE_COOLDOWN_SECONDS', 300),
    ],

    'orders_auto_sync' => [
        'interval_minutes' => (int) env('MARKETPLACE_ORDERS_AUTO_SYNC_MINUTES', 15),
    ],

    'listing_push' => [
        'debounce_seconds' => (int) env('MARKETPLACE_LISTING_PUSH_DEBOUNCE_SECONDS', 45),
        'active_run_block_seconds' => (int) env('MARKETPLACE_LISTING_PUSH_ACTIVE_RUN_BLOCK_SECONDS', 900),
        'active_statuses' => ['queued', 'processing', 'retrying'],
        'merge_statuses' => ['queued', 'retrying'],
    ],

    'order_actions' => [
        'debounce_seconds' => (int) env('MARKETPLACE_ORDER_ACTION_DEBOUNCE_SECONDS', 45),
        'active_run_block_seconds' => (int) env('MARKETPLACE_ORDER_ACTION_ACTIVE_RUN_BLOCK_SECONDS', 900),
        'active_statuses' => ['queued', 'processing', 'retrying'],
        'merge_statuses' => ['queued', 'retrying'],
    ],

    'webhook_debounce' => [
        'default_seconds' => (int) env('MARKETPLACE_WEBHOOK_DEBOUNCE_SECONDS', 30),
        'active_statuses' => ['queued', 'processing'],
    ],

    'circuit_breaker' => [
        'failure_threshold' => (int) env('MARKETPLACE_CIRCUIT_BREAKER_FAILURE_THRESHOLD', 5),
        'recovery_time_seconds' => (int) env('MARKETPLACE_CIRCUIT_BREAKER_RECOVERY_SECONDS', 300),
    ],

    'rate_limiter' => [
        'max_retries' => (int) env('MARKETPLACE_RATE_LIMITER_MAX_RETRIES', 5),
        'max_backoff_seconds' => (int) env('MARKETPLACE_RATE_LIMITER_MAX_BACKOFF', 60),
        'base_backoff_ms' => (int) env('MARKETPLACE_RATE_LIMITER_BASE_BACKOFF_MS', 1000),
        'jitter_max_ms' => (int) env('MARKETPLACE_RATE_LIMITER_JITTER_MAX_MS', 2000),
    ],

    'queues' => [
        'sync' => env('MARKETPLACE_SYNC_QUEUE', env('DB_QUEUE', 'default')),
        'listing_push' => env('MARKETPLACE_LISTING_PUSH_QUEUE', env('DB_QUEUE', 'default')),
        'order_actions' => env('MARKETPLACE_ORDER_ACTION_QUEUE', env('DB_QUEUE', 'default')),
    ],

    'features' => [
        'v2_enabled' => (bool) env('MARKETPLACE_V2_ENABLED', true),
        'overview_enabled' => (bool) env('MARKETPLACE_OVERVIEW_ENABLED', true),
        'integrations_enabled' => (bool) env('MARKETPLACE_INTEGRATIONS_ENABLED', true),
        'orders_v2_enabled' => (bool) env('MARKETPLACE_ORDERS_V2_ENABLED', true),
        'profit_center_enabled' => (bool) env('MARKETPLACE_PROFIT_CENTER_ENABLED', true),
        'trendyol_booster_enabled' => (bool) env('MARKETPLACE_TRENDYOL_BOOSTER_ENABLED', true),
        'onboarding_guide_enabled' => (bool) env('MARKETPLACE_ONBOARDING_GUIDE_ENABLED', true),
        'public_trendyol_profit_tool_enabled' => (bool) env('PUBLIC_TRENDYOL_PROFIT_TOOL_ENABLED', false),
        'pricing_simulator_enabled' => (bool) env('MARKETPLACE_PRICING_SIMULATOR_ENABLED', false),
        'settlement_audit_enabled' => (bool) env('MARKETPLACE_SETTLEMENT_AUDIT_ENABLED', false),
        'campaign_decision_center_enabled' => (bool) env('MARKETPLACE_CAMPAIGN_DECISION_CENTER_ENABLED', false),
        'risk_center_enabled' => (bool) env('MARKETPLACE_RISK_CENTER_ENABLED', false),
        'report_digest_enabled' => (bool) env('MARKETPLACE_REPORT_DIGEST_ENABLED', false),
        'products_v2_enabled' => (bool) env('MARKETPLACE_PRODUCTS_V2_ENABLED', true),
        'matching_center_enabled' => (bool) env('MARKETPLACE_MATCHING_CENTER_ENABLED', true),
        'finance_v2_enabled' => (bool) env('MARKETPLACE_FINANCE_V2_ENABLED', true),
        'questions_enabled' => (bool) env('MARKETPLACE_QUESTIONS_ENABLED', true),
        'claims_enabled' => (bool) env('MARKETPLACE_CLAIMS_ENABLED', true),
        'crm_enabled' => (bool) env('CRM_ENABLED', true),
        'order_actions_enabled' => (bool) env('MARKETPLACE_ORDER_ACTIONS_ENABLED', true),
        'package_actions_enabled' => (bool) env('MARKETPLACE_PACKAGE_ACTIONS_ENABLED', true),
        'bulk_order_actions_enabled' => (bool) env('MARKETPLACE_BULK_ORDER_ACTIONS_ENABLED', true),
        'bulk_package_actions_enabled' => (bool) env('MARKETPLACE_BULK_PACKAGE_ACTIONS_ENABLED', true),
        'listing_push_enabled' => (bool) env('MARKETPLACE_LISTING_PUSH_ENABLED', true),
        'order_action_retry_enabled' => (bool) env('MARKETPLACE_ORDER_ACTION_RETRY_ENABLED', true),
        'notifications_enabled' => (bool) env('MARKETPLACE_NOTIFICATIONS_ENABLED', true),
        'party_core_enabled' => (bool) env('PARTY_CORE_ENABLED', false),
        'accounting_enabled' => (bool) env('ACCOUNTING_ENABLED', false),
    ],

    'report_digest' => [
        'default_send_time' => env('MARKETPLACE_REPORT_DIGEST_DEFAULT_SEND_TIME', '08:30'),
        'max_subscriptions_per_run' => (int) env('MARKETPLACE_REPORT_DIGEST_MAX_SUBSCRIPTIONS_PER_RUN', 100),
    ],

    'trendyol_booster' => [
        'email_digest_enabled' => (bool) env('MARKETPLACE_TRENDYOL_BOOSTER_EMAIL_DIGEST_ENABLED', false),
        'email_digest_max_notifications' => (int) env('MARKETPLACE_TRENDYOL_BOOSTER_EMAIL_DIGEST_MAX_NOTIFICATIONS', 100),
        'request_timeout' => (int) env('MARKETPLACE_TRENDYOL_BOOSTER_REQUEST_TIMEOUT', 12),
        'request_retries' => (int) env('MARKETPLACE_TRENDYOL_BOOSTER_REQUEST_RETRIES', 1),
        'request_retry_delay_ms' => (int) env('MARKETPLACE_TRENDYOL_BOOSTER_REQUEST_RETRY_DELAY_MS', 250),
        'tracking_interval_minutes' => (int) env('MARKETPLACE_TRENDYOL_BOOSTER_TRACKING_INTERVAL_MINUTES', 60),
        'companion' => [
            'max_stock_sellers' => (int) env('MARKETPLACE_TRENDYOL_BOOSTER_COMPANION_MAX_STOCK_SELLERS', 30),
            'max_store_items' => (int) env('MARKETPLACE_TRENDYOL_BOOSTER_COMPANION_MAX_STORE_ITEMS', 200),
        ],
        'notifications' => [
            'price_min_delta_amount' => (float) env('MARKETPLACE_TRENDYOL_BOOSTER_NOTIFY_PRICE_MIN_DELTA_AMOUNT', 0.01),
            'price_min_delta_percent' => (float) env('MARKETPLACE_TRENDYOL_BOOSTER_NOTIFY_PRICE_MIN_DELTA_PERCENT', 0),
            'stock_min_delta_units' => (int) env('MARKETPLACE_TRENDYOL_BOOSTER_NOTIFY_STOCK_MIN_DELTA_UNITS', 1),
            'stock_min_estimated_sales' => (int) env('MARKETPLACE_TRENDYOL_BOOSTER_NOTIFY_STOCK_MIN_ESTIMATED_SALES', 1),
            'store_min_new_products' => (int) env('MARKETPLACE_TRENDYOL_BOOSTER_NOTIFY_STORE_MIN_NEW_PRODUCTS', 1),
            'store_min_price_changes' => (int) env('MARKETPLACE_TRENDYOL_BOOSTER_NOTIFY_STORE_MIN_PRICE_CHANGES', 1),
            'keyword_min_rank_delta' => (int) env('MARKETPLACE_TRENDYOL_BOOSTER_NOTIFY_KEYWORD_MIN_RANK_DELTA', 1),
        ],
        'market_research' => [
            'google_api_key' => env('GOOGLE_SEARCH_API_KEY', ''),
            'google_engine_id' => env('GOOGLE_SEARCH_ENGINE_ID', ''),
            'max_results' => (int) env('GOOGLE_SEARCH_MAX_RESULTS', 10),
        ],
        'sync' => [
            'scheduler_recent_minutes' => (int) env('MARKETPLACE_TRENDYOL_BOOSTER_SYNC_RECENT_MINUTES', 15),
            'product_limit' => (int) env('MARKETPLACE_TRENDYOL_BOOSTER_SYNC_PRODUCT_LIMIT', 50),
            'analysis_limit' => (int) env('MARKETPLACE_TRENDYOL_BOOSTER_SYNC_ANALYSIS_LIMIT', 100),
            'competitor_limit' => (int) env('MARKETPLACE_TRENDYOL_BOOSTER_SYNC_COMPETITOR_LIMIT', 50),
            'keyword_limit' => (int) env('MARKETPLACE_TRENDYOL_BOOSTER_SYNC_KEYWORD_LIMIT', 50),
            'store_limit' => (int) env('MARKETPLACE_TRENDYOL_BOOSTER_SYNC_STORE_LIMIT', 25),
            'product_stale_minutes' => (int) env('MARKETPLACE_TRENDYOL_BOOSTER_SYNC_PRODUCT_STALE_MINUTES', 60),
            'competitor_stale_minutes' => (int) env('MARKETPLACE_TRENDYOL_BOOSTER_SYNC_COMPETITOR_STALE_MINUTES', 240),
            'keyword_stale_minutes' => (int) env('MARKETPLACE_TRENDYOL_BOOSTER_SYNC_KEYWORD_STALE_MINUTES', 360),
            'store_stale_minutes' => (int) env('MARKETPLACE_TRENDYOL_BOOSTER_SYNC_STORE_STALE_MINUTES', 720),
        ],
        'alerts' => [
            'cache_seconds' => (int) env('MARKETPLACE_TRENDYOL_BOOSTER_ALERT_CACHE_SECONDS', 30),
            'scheduler_critical_multiplier' => (int) env('MARKETPLACE_TRENDYOL_BOOSTER_ALERT_SCHEDULER_CRITICAL_MULTIPLIER', 3),
            'backlog_warning_min' => (int) env('MARKETPLACE_TRENDYOL_BOOSTER_ALERT_BACKLOG_WARNING_MIN', 10),
            'backlog_warning_ratio' => (float) env('MARKETPLACE_TRENDYOL_BOOSTER_ALERT_BACKLOG_WARNING_RATIO', 50),
            'backlog_critical_min' => (int) env('MARKETPLACE_TRENDYOL_BOOSTER_ALERT_BACKLOG_CRITICAL_MIN', 50),
            'backlog_critical_ratio' => (float) env('MARKETPLACE_TRENDYOL_BOOSTER_ALERT_BACKLOG_CRITICAL_RATIO', 80),
            'never_checked_warning_min' => (int) env('MARKETPLACE_TRENDYOL_BOOSTER_ALERT_NEVER_CHECKED_WARNING_MIN', 10),
            'retention_warning_min' => (int) env('MARKETPLACE_TRENDYOL_BOOSTER_ALERT_RETENTION_WARNING_MIN', 1000),
            'retention_warning_ratio' => (float) env('MARKETPLACE_TRENDYOL_BOOSTER_ALERT_RETENTION_WARNING_RATIO', 25),
        ],
        'decision_actions' => [
            'scan_limit' => (int) env('MARKETPLACE_TRENDYOL_BOOSTER_ACTION_SCAN_LIMIT', 200),
            'display_limit' => (int) env('MARKETPLACE_TRENDYOL_BOOSTER_ACTION_DISPLAY_LIMIT', 3),
            'high_risk_score' => (int) env('MARKETPLACE_TRENDYOL_BOOSTER_ACTION_HIGH_RISK_SCORE', 60),
            'low_quality_score' => (int) env('MARKETPLACE_TRENDYOL_BOOSTER_ACTION_LOW_QUALITY_SCORE', 40),
            'critical_stock_days' => (float) env('MARKETPLACE_TRENDYOL_BOOSTER_ACTION_CRITICAL_STOCK_DAYS', 3),
            'stock_min_confidence' => (int) env('MARKETPLACE_TRENDYOL_BOOSTER_ACTION_STOCK_MIN_CONFIDENCE', 50),
        ],
        'retention' => [
            'cleanup_enabled' => (bool) env('MARKETPLACE_TRENDYOL_BOOSTER_RETENTION_CLEANUP_ENABLED', false),
            'cleanup_batch_size' => (int) env('MARKETPLACE_TRENDYOL_BOOSTER_RETENTION_CLEANUP_BATCH_SIZE', 500),
            'cleanup_max_delete_per_run' => (int) env('MARKETPLACE_TRENDYOL_BOOSTER_RETENTION_CLEANUP_MAX_DELETE_PER_RUN', 10000),
            'snapshots_days' => (int) env('MARKETPLACE_TRENDYOL_BOOSTER_RETENTION_SNAPSHOTS_DAYS', 180),
            'stock_checks_days' => (int) env('MARKETPLACE_TRENDYOL_BOOSTER_RETENTION_STOCK_CHECKS_DAYS', 180),
            'stock_sellers_days' => (int) env('MARKETPLACE_TRENDYOL_BOOSTER_RETENTION_STOCK_SELLERS_DAYS', 180),
            'keyword_lookups_days' => (int) env('MARKETPLACE_TRENDYOL_BOOSTER_RETENTION_KEYWORD_LOOKUPS_DAYS', 180),
            'keyword_observations_days' => (int) env('MARKETPLACE_TRENDYOL_BOOSTER_RETENTION_KEYWORD_OBSERVATIONS_DAYS', 180),
            'store_snapshots_days' => (int) env('MARKETPLACE_TRENDYOL_BOOSTER_RETENTION_STORE_SNAPSHOTS_DAYS', 180),
            'store_item_histories_days' => (int) env('MARKETPLACE_TRENDYOL_BOOSTER_RETENTION_STORE_ITEM_HISTORIES_DAYS', 180),
            'supplier_offers_days' => (int) env('MARKETPLACE_TRENDYOL_BOOSTER_RETENTION_SUPPLIER_OFFERS_DAYS', 180),
            'bestseller_runs_days' => (int) env('MARKETPLACE_TRENDYOL_BOOSTER_RETENTION_BESTSELLER_RUNS_DAYS', 365),
            'bestseller_items_days' => (int) env('MARKETPLACE_TRENDYOL_BOOSTER_RETENTION_BESTSELLER_ITEMS_DAYS', 365),
            'activity_logs_days' => (int) env('MARKETPLACE_TRENDYOL_BOOSTER_RETENTION_ACTIVITY_LOGS_DAYS', 90),
        ],
    ],

    'trendyol' => [
        'base_url' => env('TRENDYOL_API_BASE_URL', 'https://apigw.trendyol.com/'),
        'request_timeout' => (int) env('TRENDYOL_REQUEST_TIMEOUT', 30),
        'webhook_debounce_seconds' => (int) env('TRENDYOL_WEBHOOK_DEBOUNCE_SECONDS', 30),
        'page_size' => (int) env('TRENDYOL_ORDER_PAGE_SIZE', 200),
        'order_history_limit_days' => (int) env('TRENDYOL_ORDER_HISTORY_LIMIT_DAYS', 30),
        'product_page_size' => (int) env('TRENDYOL_PRODUCT_PAGE_SIZE', 100),
        'finance_page_size' => (int) env('TRENDYOL_FINANCE_PAGE_SIZE', 500),
        'claims_page_size' => (int) env('TRENDYOL_CLAIMS_PAGE_SIZE', 50),
        'max_claim_pages_per_sync' => (int) env('TRENDYOL_MAX_CLAIM_PAGES_PER_SYNC', 20),
        'claim_issue_reason_id' => (int) env('TRENDYOL_CLAIM_ISSUE_REASON_ID', 451),
        'order_stream_enabled' => (bool) env('TRENDYOL_ORDER_STREAM_ENABLED', true),
        'buybox_sync_enabled' => (bool) env('TRENDYOL_BUYBOX_SYNC_ENABLED', false), // Safe default
        'cargo_invoice_sync_enabled' => (bool) env('TRENDYOL_CARGO_INVOICE_SYNC_ENABLED', false), // Safe default
        'reference_sync_enabled' => (bool) env('TRENDYOL_REFERENCE_SYNC_ENABLED', false), // Safe default
        'batch_tracking_enabled' => (bool) env('TRENDYOL_BATCH_TRACKING_ENABLED', false), // Safe default
        'price_recommendations_enabled' => (bool) env('TRENDYOL_PRICE_RECOMMENDATIONS_ENABLED', false),
        'manual_price_actions_enabled' => (bool) env('TRENDYOL_MANUAL_PRICE_ACTIONS_ENABLED', false),
        'bulk_price_actions_enabled' => (bool) env('TRENDYOL_BULK_PRICE_ACTIONS_ENABLED', false),
        'automatic_price_actions_enabled' => (bool) env('TRENDYOL_AUTOMATIC_PRICE_ACTIONS_ENABLED', false),
        'price_rollback_enabled' => (bool) env('TRENDYOL_PRICE_ROLLBACK_ENABLED', false),
        // Sağlık Merkezi scheduler gecikme eşikleri (dakika)
        'health' => [
            'warning_multiplier' => (int) env('TRENDYOL_HEALTH_WARNING_MULTIPLIER', 2),
            'critical_multiplier' => (int) env('TRENDYOL_HEALTH_CRITICAL_MULTIPLIER', 4),
            'order_stream_interval_minutes' => (int) env('TRENDYOL_HEALTH_ORDER_STREAM_INTERVAL_MINUTES', 15),
            'buybox_interval_minutes' => (int) env('TRENDYOL_HEALTH_BUYBOX_INTERVAL_MINUTES', 30),
            'cargo_invoice_interval_minutes' => (int) env('TRENDYOL_HEALTH_CARGO_INVOICE_INTERVAL_MINUTES', 1440),
            'reference_interval_minutes' => (int) env('TRENDYOL_HEALTH_REFERENCE_INTERVAL_MINUTES', 10080),
        ],
        'sync_defaults' => [
            'orders_poll_minutes' => 15,
            'finance_poll_minutes' => 60,
            'products_poll_minutes' => 720,
            'claims_poll_minutes' => 30,
            'backfill_mode' => '7_days',
            'backfill_days' => 7,
            'price_push_enabled' => false,
            'stock_push_enabled' => false,
            'max_parallel_jobs' => 1,
            'request_jitter_seconds' => 5,
        ],
        'user_agent_suffix' => env('TRENDYOL_USER_AGENT_SUFFIX', 'ZOLM Marketplace Integration'),
        'settlement_transaction_types' => [
            'Sale',
            'Return',
            'Discount',
            'DiscountCancel',
            'Coupon',
            'CouponCancel',
            'ProvisionPositive',
            'ProvisionNegative',
            'SellerRevenuePositive',
            'SellerRevenueNegative',
            'CommissionPositive',
            'CommissionNegative',
            'SellerRevenuePositiveCancel',
            'SellerRevenueNegativeCancel',
            'CommissionPositiveCancel',
            'CommissionNegativeCancel',
        ],
        'other_financial_transaction_types' => [
            'Stoppage',
            'PaymentOrder',
            'DeductionInvoices',
        ],
    ],

    'hepsiburada' => [
        'oms_base_url' => env('HEPSIBURADA_OMS_BASE_URL', 'https://oms-external.hepsiburada.com/'),
        'listing_base_url' => env('HEPSIBURADA_LISTING_BASE_URL', 'https://listing-external.hepsiburada.com/'),
        'finance_base_url' => env('HEPSIBURADA_FINANCE_BASE_URL', 'https://mpfinance-external.hepsiburada.com/'),
        'product_base_url' => env('HEPSIBURADA_PRODUCT_BASE_URL', 'https://mpop.hepsiburada.com/'),
        'question_base_url' => env('HEPSIBURADA_QUESTION_BASE_URL', 'https://api-asktoseller-merchant-sit.hepsiburada.com/api/v1.0/'),
        'request_timeout' => (int) env('HEPSIBURADA_REQUEST_TIMEOUT', 45),
        'order_page_size' => (int) env('HEPSIBURADA_ORDER_PAGE_SIZE', 50),
        'open_package_page_size' => (int) env('HEPSIBURADA_OPEN_PACKAGE_PAGE_SIZE', 10),
        'package_page_size' => (int) env('HEPSIBURADA_PACKAGE_PAGE_SIZE', 50),
        'product_page_size' => (int) env('HEPSIBURADA_PRODUCT_PAGE_SIZE', 100),
        'finance_page_size' => (int) env('HEPSIBURADA_FINANCE_PAGE_SIZE', 100),
        'question_page_size' => (int) env('HEPSIBURADA_QUESTION_PAGE_SIZE', 100),
        'claim_base_url' => env('HEPSIBURADA_CLAIM_BASE_URL', env('HEPSIBURADA_OMS_BASE_URL', 'https://oms-external.hepsiburada.com/')),
        'claim_page_size' => (int) env('HEPSIBURADA_CLAIM_PAGE_SIZE', 50),
        'claim_list_path' => env('HEPSIBURADA_CLAIM_LIST_PATH', 'claims/merchantid/{merchantId}'),
        'claim_accept_path' => env('HEPSIBURADA_CLAIM_ACCEPT_PATH', 'claims/number/{claimNumber}/accept'),
        'claim_reject_path' => env('HEPSIBURADA_CLAIM_REJECT_PATH', 'claims/number/{claimNumber}/reject'),
        'max_pages_per_request' => (int) env('HEPSIBURADA_MAX_PAGES_PER_REQUEST', 50),
        'max_question_pages_per_sync' => (int) env('HEPSIBURADA_MAX_QUESTION_PAGES_PER_SYNC', 10),
        'sync_defaults' => [
            'orders_poll_minutes' => 15,
            'finance_poll_minutes' => 120,
            'products_poll_minutes' => 720,
            'claims_poll_minutes' => 30,
            'backfill_mode' => '7_days',
            'backfill_days' => 7,
            'webhook_enabled' => false,
            'price_push_enabled' => false,
            'stock_push_enabled' => false,
            'max_parallel_jobs' => 1,
            'request_jitter_seconds' => 10,
        ],
        'user_agent_suffix' => env('HEPSIBURADA_USER_AGENT_SUFFIX', 'ZOLM Marketplace Integration'),
    ],

    'n11' => [
        'base_url' => env('N11_API_BASE_URL', 'https://api.n11.com'),
        'soap_url' => env('N11_SOAP_URL', 'https://api.n11.com/ws/productService/'),
        'request_timeout' => (int) env('N11_REQUEST_TIMEOUT', 45),
        'order_page_size' => (int) env('N11_ORDER_PAGE_SIZE', 100),
        'product_page_size' => (int) env('N11_PRODUCT_PAGE_SIZE', 20),
        'question_page_size' => (int) env('N11_QUESTION_PAGE_SIZE', 50),
        'claim_page_size' => (int) env('N11_CLAIM_PAGE_SIZE', 50),
        'return_soap_url' => env('N11_RETURN_SOAP_URL', 'https://api.n11.com/ws/ReturnService/'),
        'claim_list_operation' => env('N11_CLAIM_LIST_OPERATION', 'ClaimReturnList'),
        'claim_approve_operation' => env('N11_CLAIM_APPROVE_OPERATION', 'ClaimReturnApprove'),
        'claim_reject_operation' => env('N11_CLAIM_REJECT_OPERATION', 'ClaimReturnDeny'),
        'max_question_pages_per_sync' => (int) env('N11_MAX_QUESTION_PAGES_PER_SYNC', 10),
        'max_claim_pages_per_sync' => (int) env('N11_MAX_CLAIM_PAGES_PER_SYNC', 20),
        'sync_defaults' => [
            'orders_poll_minutes' => 15,
            'finance_poll_minutes' => 360,
            'products_poll_minutes' => 360,
            'claims_poll_minutes' => 30,
            'backfill_mode' => '7_days',
            'backfill_days' => 7,
            'finance_enabled' => false,
            'webhook_enabled' => false,
            'price_push_enabled' => false,
            'stock_push_enabled' => false,
            'max_parallel_jobs' => 1,
            'request_jitter_seconds' => 10,
        ],
    ],

    'pazarama' => [
        'base_url' => env('PAZARAMA_API_BASE_URL', 'https://isortagimapi.pazarama.com'),
        'token_url' => env('PAZARAMA_TOKEN_URL', 'https://isortagimgiris.pazarama.com/connect/token'),
        'request_timeout' => (int) env('PAZARAMA_REQUEST_TIMEOUT', 45),
        'order_page_size' => (int) env('PAZARAMA_ORDER_PAGE_SIZE', 500),
        'product_page_size' => (int) env('PAZARAMA_PRODUCT_PAGE_SIZE', 100),
        'question_page_size' => (int) env('PAZARAMA_QUESTION_PAGE_SIZE', 100),
        'claim_page_size' => (int) env('PAZARAMA_CLAIM_PAGE_SIZE', 100),
        'question_list_path' => env('PAZARAMA_QUESTION_LIST_PATH', 'question/getQuestionsForApi'),
        'question_answer_path' => env('PAZARAMA_QUESTION_ANSWER_PATH', 'question/answerQuestionForApi'),
        'question_list_method' => env('PAZARAMA_QUESTION_LIST_METHOD', 'POST'),
        'max_order_pages_per_sync' => (int) env('PAZARAMA_MAX_ORDER_PAGES_PER_SYNC', 20),
        'max_product_pages_per_sync' => (int) env('PAZARAMA_MAX_PRODUCT_PAGES_PER_SYNC', 20),
        'max_question_pages_per_sync' => (int) env('PAZARAMA_MAX_QUESTION_PAGES_PER_SYNC', 10),
        'sync_defaults' => [
            'orders_poll_minutes' => 15,
            'finance_poll_minutes' => 360,
            'products_poll_minutes' => 720,
            'claims_poll_minutes' => 30,
            'backfill_mode' => '7_days',
            'backfill_days' => 7,
            'finance_enabled' => false,
            'webhook_enabled' => false,
            'price_push_enabled' => false,
            'stock_push_enabled' => false,
            'max_parallel_jobs' => 1,
            'request_jitter_seconds' => 10,
        ],
    ],

    'amazon' => [
        'base_url' => env('AMAZON_API_BASE_URL', ''),
        'request_timeout' => (int) env('AMAZON_REQUEST_TIMEOUT', 45),
    ],

    'koctas' => [
        'base_url' => env('KOCTAS_API_BASE_URL', 'https://koctas.mirakl.net'),
        'request_timeout' => (int) env('KOCTAS_REQUEST_TIMEOUT', 45),
        'commission_rate' => (float) env('KOCTAS_COMMISSION_RATE', 15),
        'order_page_size' => (int) env('KOCTAS_ORDER_PAGE_SIZE', 50),
        'product_page_size' => (int) env('KOCTAS_PRODUCT_PAGE_SIZE', 100),
        'question_page_size' => (int) env('KOCTAS_QUESTION_PAGE_SIZE', 50),
        'claim_page_size' => (int) env('KOCTAS_CLAIM_PAGE_SIZE', 50),
        'question_list_path' => env('KOCTAS_QUESTION_LIST_PATH', 'api/inbox/threads'),
        'question_answer_path' => env('KOCTAS_QUESTION_ANSWER_PATH', 'api/inbox/threads/{thread_id}/messages'),
        'return_list_path' => env('KOCTAS_RETURN_LIST_PATH', 'api/returns'),
        'return_accept_path' => env('KOCTAS_RETURN_ACCEPT_PATH', 'api/returns/{return_id}/accept'),
        'return_reject_path' => env('KOCTAS_RETURN_REJECT_PATH', 'api/returns/{return_id}/refuse'),
        'max_order_pages_per_sync' => (int) env('KOCTAS_MAX_ORDER_PAGES_PER_SYNC', 20),
        'max_product_pages_per_sync' => (int) env('KOCTAS_MAX_PRODUCT_PAGES_PER_SYNC', 20),
        'max_question_pages_per_sync' => (int) env('KOCTAS_MAX_QUESTION_PAGES_PER_SYNC', 10),
        'sync_defaults' => [
            'orders_poll_minutes' => 15,
            'finance_poll_minutes' => 360,
            'products_poll_minutes' => 720,
            'claims_poll_minutes' => 30,
            'backfill_mode' => '7_days',
            'backfill_days' => 7,
            'finance_enabled' => false,
            'webhook_enabled' => false,
            'price_push_enabled' => false,
            'stock_push_enabled' => false,
            'max_parallel_jobs' => 1,
            'request_jitter_seconds' => 15,
        ],
    ],

    'ciceksepeti' => [
        'base_url' => env('CICEKSEPETI_API_BASE_URL', 'https://apis.ciceksepeti.com/api/v1'),
        'request_timeout' => (int) env('CICEKSEPETI_REQUEST_TIMEOUT', 45),
        'order_page_size' => (int) env('CICEKSEPETI_ORDER_PAGE_SIZE', 100),
        'product_page_size' => (int) env('CICEKSEPETI_PRODUCT_PAGE_SIZE', 60),
        'question_page_size' => (int) env('CICEKSEPETI_QUESTION_PAGE_SIZE', 100),
        'claim_page_size' => (int) env('CICEKSEPETI_CLAIM_PAGE_SIZE', 100),
        'question_list_path' => env('CICEKSEPETI_QUESTION_LIST_PATH', 'sellerquestions'),
        'question_answer_path' => env('CICEKSEPETI_QUESTION_ANSWER_PATH', 'sellerquestions/{id}'),
        'question_list_method' => env('CICEKSEPETI_QUESTION_LIST_METHOD', 'GET'),
        'question_answer_method' => env('CICEKSEPETI_QUESTION_ANSWER_METHOD', 'PUT'),
        'question_timestamp_unit' => env('CICEKSEPETI_QUESTION_TIMESTAMP_UNIT', 'date'),
        'question_branch_action_ids' => env('CICEKSEPETI_QUESTION_BRANCH_ACTION_IDS', 'all'),
        'question_first_page' => (int) env('CICEKSEPETI_QUESTION_FIRST_PAGE', 1),
        'max_order_pages_per_sync' => (int) env('CICEKSEPETI_MAX_ORDER_PAGES_PER_SYNC', 20),
        'max_product_pages_per_sync' => (int) env('CICEKSEPETI_MAX_PRODUCT_PAGES_PER_SYNC', 20),
        'max_question_pages_per_sync' => (int) env('CICEKSEPETI_MAX_QUESTION_PAGES_PER_SYNC', 10),
        'product_rate_limit_max_attempts' => (int) env('CICEKSEPETI_PRODUCT_RATE_LIMIT_MAX_ATTEMPTS', 3),
        'product_rate_limit_grace_seconds' => (int) env('CICEKSEPETI_PRODUCT_RATE_LIMIT_GRACE_SECONDS', 1),
        'sync_defaults' => [
            'orders_poll_minutes' => 15,
            'finance_poll_minutes' => 360,
            'products_poll_minutes' => 720,
            'claims_poll_minutes' => 30,
            'backfill_mode' => '7_days',
            'backfill_days' => 7,
            'finance_enabled' => false,
            'webhook_enabled' => false,
            'price_push_enabled' => false,
            'stock_push_enabled' => false,
            'max_parallel_jobs' => 1,
            'request_jitter_seconds' => 10,
        ],
    ],

    'woocommerce' => [
        'base_url' => env('WOOCOMMERCE_API_BASE_URL', ''),
        'request_timeout' => (int) env('WOOCOMMERCE_REQUEST_TIMEOUT', 30),
        'webhook_debounce_seconds' => (int) env('WOOCOMMERCE_WEBHOOK_DEBOUNCE_SECONDS', 120),
        'order_page_size' => (int) env('WOOCOMMERCE_ORDER_PAGE_SIZE', 25),
        'product_page_size' => (int) env('WOOCOMMERCE_PRODUCT_PAGE_SIZE', 25),
        'question_page_size' => (int) env('WOOCOMMERCE_QUESTION_PAGE_SIZE', 50),
        'claim_page_size' => (int) env('WOOCOMMERCE_CLAIM_PAGE_SIZE', 25),
        'max_pages_per_sync' => (int) env('WOOCOMMERCE_MAX_PAGES_PER_SYNC', 10),
        'batch_size' => (int) env('WOOCOMMERCE_BATCH_SIZE', 25),
        'batch_push_enabled' => (bool) env('WOOCOMMERCE_BATCH_PUSH_ENABLED', true),
        'version' => env('WOOCOMMERCE_API_VERSION', 'wc/v3'),
        'public_product_path' => env('WOOCOMMERCE_PUBLIC_PRODUCT_PATH', 'magaza'),
        'order_fields' => [
            'id',
            'number',
            'status',
            'date_created',
            'date_created_gmt',
            'date_modified',
            'date_modified_gmt',
            'billing',
            'shipping',
            'shipping_lines',
            'line_items',
        ],
        'product_fields' => [
            'id',
            'parent_id',
            'type',
            'permalink',
            'sku',
            'name',
            'status',
            'price',
            'regular_price',
            'manage_stock',
            'stock_quantity',
            'date_created',
            'date_created_gmt',
            'date_modified',
            'date_modified_gmt',
            'categories',
            'brands',
        ],
        'variation_fields' => [
            'id',
            'parent_id',
            'permalink',
            'sku',
            'status',
            'price',
            'regular_price',
            'manage_stock',
            'stock_quantity',
            'date_created',
            'date_created_gmt',
            'date_modified',
            'date_modified_gmt',
            'attributes',
        ],
        'sync_defaults' => [
            'orders_poll_minutes' => 15,
            'finance_poll_minutes' => 360,
            'products_poll_minutes' => 720,
            'claims_poll_minutes' => 30,
            'backfill_mode' => '7_days',
            'backfill_days' => 7,
            'finance_enabled' => false,
            'price_push_enabled' => false,
            'stock_push_enabled' => false,
            'max_parallel_jobs' => 1,
            'request_jitter_seconds' => 15,
        ],
    ],

    'shopify' => [
        'base_url' => env('SHOPIFY_API_BASE_URL', ''),
        'request_timeout' => (int) env('SHOPIFY_REQUEST_TIMEOUT', 45),
        'webhook_debounce_seconds' => (int) env('SHOPIFY_WEBHOOK_DEBOUNCE_SECONDS', 45),
        'api_version' => env('SHOPIFY_API_VERSION', '2025-10'),
        'order_page_size' => (int) env('SHOPIFY_ORDER_PAGE_SIZE', 50),
        'product_page_size' => (int) env('SHOPIFY_PRODUCT_PAGE_SIZE', 50),
        'finance_page_size' => (int) env('SHOPIFY_FINANCE_PAGE_SIZE', 25),
        'sync_defaults' => [
            'orders_poll_minutes' => 15,
            'finance_poll_minutes' => 240,
            'products_poll_minutes' => 720,
            'backfill_mode' => '7_days',
            'backfill_days' => 7,
            'price_push_enabled' => false,
            'stock_push_enabled' => false,
            'max_parallel_jobs' => 1,
            'request_jitter_seconds' => 10,
        ],
    ],
];
