<?php

return [
    'manual_sync' => [
        'debounce_seconds' => (int) env('MARKETPLACE_MANUAL_SYNC_DEBOUNCE_SECONDS', 30),
        'active_run_block_seconds' => (int) env('MARKETPLACE_MANUAL_SYNC_ACTIVE_RUN_BLOCK_SECONDS', 900),
        'active_statuses' => ['queued', 'processing', 'retrying'],
    ],

    'listing_push' => [
        'debounce_seconds' => (int) env('MARKETPLACE_LISTING_PUSH_DEBOUNCE_SECONDS', 45),
        'active_run_block_seconds' => (int) env('MARKETPLACE_LISTING_PUSH_ACTIVE_RUN_BLOCK_SECONDS', 900),
        'active_statuses' => ['queued', 'processing', 'retrying'],
        'merge_statuses' => ['queued', 'retrying'],
    ],

    'order_actions' => [
        'debounce_seconds' => (int) env('MARKETPLACE_ORDER_ACTION_DEBOUNCE_SECONDS', 45),
        'active_run_block_seconds' => (int) env('MARKETPLACE_ORDER_ACTION_ACTIVE_RUN_BLOCK_SECONDS', 900),
        'active_statuses' => ['queued', 'processing', 'retrying'],
        'merge_statuses' => ['queued', 'retrying'],
    ],

    'webhook_debounce' => [
        'default_seconds' => (int) env('MARKETPLACE_WEBHOOK_DEBOUNCE_SECONDS', 30),
        'active_statuses' => ['queued', 'processing'],
    ],

    'circuit_breaker' => [
        'failure_threshold' => (int) env('MARKETPLACE_CIRCUIT_BREAKER_FAILURE_THRESHOLD', 5),
        'recovery_time_seconds' => (int) env('MARKETPLACE_CIRCUIT_BREAKER_RECOVERY_SECONDS', 300),
    ],

    'rate_limiter' => [
        'max_retries' => (int) env('MARKETPLACE_RATE_LIMITER_MAX_RETRIES', 5),
        'max_backoff_seconds' => (int) env('MARKETPLACE_RATE_LIMITER_MAX_BACKOFF', 60),
        'base_backoff_ms' => (int) env('MARKETPLACE_RATE_LIMITER_BASE_BACKOFF_MS', 1000),
        'jitter_max_ms' => (int) env('MARKETPLACE_RATE_LIMITER_JITTER_MAX_MS', 2000),
    ],

    'features' => [
        'v2_enabled' => (bool) env('MARKETPLACE_V2_ENABLED', true),
        'overview_enabled' => (bool) env('MARKETPLACE_OVERVIEW_ENABLED', true),
        'integrations_enabled' => (bool) env('MARKETPLACE_INTEGRATIONS_ENABLED', true),
        'orders_v2_enabled' => (bool) env('MARKETPLACE_ORDERS_V2_ENABLED', true),
        'products_v2_enabled' => (bool) env('MARKETPLACE_PRODUCTS_V2_ENABLED', true),
        'matching_center_enabled' => (bool) env('MARKETPLACE_MATCHING_CENTER_ENABLED', true),
        'finance_v2_enabled' => (bool) env('MARKETPLACE_FINANCE_V2_ENABLED', true),
        'order_actions_enabled' => (bool) env('MARKETPLACE_ORDER_ACTIONS_ENABLED', true),
        'package_actions_enabled' => (bool) env('MARKETPLACE_PACKAGE_ACTIONS_ENABLED', true),
        'bulk_order_actions_enabled' => (bool) env('MARKETPLACE_BULK_ORDER_ACTIONS_ENABLED', true),
        'bulk_package_actions_enabled' => (bool) env('MARKETPLACE_BULK_PACKAGE_ACTIONS_ENABLED', true),
        'listing_push_enabled' => (bool) env('MARKETPLACE_LISTING_PUSH_ENABLED', true),
        'order_action_retry_enabled' => (bool) env('MARKETPLACE_ORDER_ACTION_RETRY_ENABLED', true),
    ],

    'trendyol' => [
        'base_url' => env('TRENDYOL_API_BASE_URL', 'https://apigw.trendyol.com/'),
        'request_timeout' => (int) env('TRENDYOL_REQUEST_TIMEOUT', 30),
        'webhook_debounce_seconds' => (int) env('TRENDYOL_WEBHOOK_DEBOUNCE_SECONDS', 30),
        'page_size' => (int) env('TRENDYOL_ORDER_PAGE_SIZE', 200),
        'order_history_limit_days' => (int) env('TRENDYOL_ORDER_HISTORY_LIMIT_DAYS', 30),
        'product_page_size' => (int) env('TRENDYOL_PRODUCT_PAGE_SIZE', 100),
        'finance_page_size' => (int) env('TRENDYOL_FINANCE_PAGE_SIZE', 500),
        'sync_defaults' => [
            'orders_poll_minutes' => 15,
            'finance_poll_minutes' => 60,
            'products_poll_minutes' => 720,
            'backfill_mode' => '7_days',
            'backfill_days' => 7,
            'price_push_enabled' => false,
            'stock_push_enabled' => false,
            'max_parallel_jobs' => 1,
            'request_jitter_seconds' => 5,
        ],
        'user_agent_suffix' => env('TRENDYOL_USER_AGENT_SUFFIX', 'ZOLM Marketplace Integration'),
        'settlement_transaction_types' => [
            'Sale',
            'Return',
            'Discount',
            'DiscountCancel',
            'Coupon',
            'CouponCancel',
            'ProvisionPositive',
            'ProvisionNegative',
            'SellerRevenuePositive',
            'SellerRevenueNegative',
            'CommissionPositive',
            'CommissionNegative',
            'SellerRevenuePositiveCancel',
            'SellerRevenueNegativeCancel',
            'CommissionPositiveCancel',
            'CommissionNegativeCancel',
        ],
        'other_financial_transaction_types' => [
            'Stoppage',
            'PaymentOrder',
            'DeductionInvoices',
        ],
    ],

    'hepsiburada' => [
        'oms_base_url' => env('HEPSIBURADA_OMS_BASE_URL', 'https://oms-external.hepsiburada.com/'),
        'listing_base_url' => env('HEPSIBURADA_LISTING_BASE_URL', 'https://listing-external.hepsiburada.com/'),
        'finance_base_url' => env('HEPSIBURADA_FINANCE_BASE_URL', 'https://mpfinance-external.hepsiburada.com/'),
        'product_base_url' => env('HEPSIBURADA_PRODUCT_BASE_URL', 'https://mpop.hepsiburada.com/'),
        'request_timeout' => (int) env('HEPSIBURADA_REQUEST_TIMEOUT', 45),
        'order_page_size' => (int) env('HEPSIBURADA_ORDER_PAGE_SIZE', 50),
        'open_package_page_size' => (int) env('HEPSIBURADA_OPEN_PACKAGE_PAGE_SIZE', 10),
        'package_page_size' => (int) env('HEPSIBURADA_PACKAGE_PAGE_SIZE', 50),
        'product_page_size' => (int) env('HEPSIBURADA_PRODUCT_PAGE_SIZE', 100),
        'finance_page_size' => (int) env('HEPSIBURADA_FINANCE_PAGE_SIZE', 100),
        'max_pages_per_request' => (int) env('HEPSIBURADA_MAX_PAGES_PER_REQUEST', 50),
        'sync_defaults' => [
            'orders_poll_minutes' => 20,
            'finance_poll_minutes' => 120,
            'products_poll_minutes' => 720,
            'backfill_mode' => '7_days',
            'backfill_days' => 7,
            'webhook_enabled' => false,
            'price_push_enabled' => false,
            'stock_push_enabled' => false,
            'max_parallel_jobs' => 1,
            'request_jitter_seconds' => 10,
        ],
        'user_agent_suffix' => env('HEPSIBURADA_USER_AGENT_SUFFIX', 'ZOLM Marketplace Integration'),
    ],

    'n11' => [
        'base_url' => env('N11_API_BASE_URL', 'https://api.n11.com'),
        'request_timeout' => (int) env('N11_REQUEST_TIMEOUT', 45),
        'order_page_size' => (int) env('N11_ORDER_PAGE_SIZE', 100),
        'product_page_size' => (int) env('N11_PRODUCT_PAGE_SIZE', 20),
        'sync_defaults' => [
            'orders_poll_minutes' => 20,
            'finance_poll_minutes' => 360,
            'products_poll_minutes' => 360,
            'backfill_mode' => '7_days',
            'backfill_days' => 7,
            'finance_enabled' => false,
            'webhook_enabled' => false,
            'price_push_enabled' => false,
            'stock_push_enabled' => false,
            'max_parallel_jobs' => 1,
            'request_jitter_seconds' => 10,
        ],
    ],

    'pazarama' => [
        'base_url' => env('PAZARAMA_API_BASE_URL', 'https://isortagimapi.pazarama.com'),
        'token_url' => env('PAZARAMA_TOKEN_URL', 'https://isortagimgiris.pazarama.com/connect/token'),
        'request_timeout' => (int) env('PAZARAMA_REQUEST_TIMEOUT', 45),
        'order_page_size' => (int) env('PAZARAMA_ORDER_PAGE_SIZE', 500),
        'product_page_size' => (int) env('PAZARAMA_PRODUCT_PAGE_SIZE', 100),
        'max_order_pages_per_sync' => (int) env('PAZARAMA_MAX_ORDER_PAGES_PER_SYNC', 20),
        'max_product_pages_per_sync' => (int) env('PAZARAMA_MAX_PRODUCT_PAGES_PER_SYNC', 20),
        'sync_defaults' => [
            'orders_poll_minutes' => 20,
            'finance_poll_minutes' => 360,
            'products_poll_minutes' => 720,
            'backfill_mode' => '7_days',
            'backfill_days' => 7,
            'finance_enabled' => false,
            'webhook_enabled' => false,
            'price_push_enabled' => false,
            'stock_push_enabled' => false,
            'max_parallel_jobs' => 1,
            'request_jitter_seconds' => 10,
        ],
    ],

    'amazon' => [
        'base_url' => env('AMAZON_API_BASE_URL', ''),
        'request_timeout' => (int) env('AMAZON_REQUEST_TIMEOUT', 45),
    ],

    'koctas' => [
        'base_url' => env('KOCTAS_API_BASE_URL', 'https://koctas.mirakl.net'),
        'request_timeout' => (int) env('KOCTAS_REQUEST_TIMEOUT', 45),
        'order_page_size' => (int) env('KOCTAS_ORDER_PAGE_SIZE', 50),
        'product_page_size' => (int) env('KOCTAS_PRODUCT_PAGE_SIZE', 100),
        'max_order_pages_per_sync' => (int) env('KOCTAS_MAX_ORDER_PAGES_PER_SYNC', 20),
        'max_product_pages_per_sync' => (int) env('KOCTAS_MAX_PRODUCT_PAGES_PER_SYNC', 20),
        'sync_defaults' => [
            'orders_poll_minutes' => 20,
            'finance_poll_minutes' => 360,
            'products_poll_minutes' => 720,
            'backfill_mode' => '7_days',
            'backfill_days' => 7,
            'finance_enabled' => false,
            'webhook_enabled' => false,
            'price_push_enabled' => false,
            'stock_push_enabled' => false,
            'max_parallel_jobs' => 1,
            'request_jitter_seconds' => 15,
        ],
    ],

    'ciceksepeti' => [
        'base_url' => env('CICEKSEPETI_API_BASE_URL', 'https://apis.ciceksepeti.com/api/v1'),
        'request_timeout' => (int) env('CICEKSEPETI_REQUEST_TIMEOUT', 45),
        'order_page_size' => (int) env('CICEKSEPETI_ORDER_PAGE_SIZE', 100),
        'product_page_size' => (int) env('CICEKSEPETI_PRODUCT_PAGE_SIZE', 60),
        'max_order_pages_per_sync' => (int) env('CICEKSEPETI_MAX_ORDER_PAGES_PER_SYNC', 20),
        'max_product_pages_per_sync' => (int) env('CICEKSEPETI_MAX_PRODUCT_PAGES_PER_SYNC', 20),
        'product_rate_limit_max_attempts' => (int) env('CICEKSEPETI_PRODUCT_RATE_LIMIT_MAX_ATTEMPTS', 3),
        'product_rate_limit_grace_seconds' => (int) env('CICEKSEPETI_PRODUCT_RATE_LIMIT_GRACE_SECONDS', 1),
        'sync_defaults' => [
            'orders_poll_minutes' => 20,
            'finance_poll_minutes' => 360,
            'products_poll_minutes' => 720,
            'backfill_mode' => '7_days',
            'backfill_days' => 7,
            'finance_enabled' => false,
            'webhook_enabled' => false,
            'price_push_enabled' => false,
            'stock_push_enabled' => false,
            'max_parallel_jobs' => 1,
            'request_jitter_seconds' => 10,
        ],
    ],

    'woocommerce' => [
        'base_url' => env('WOOCOMMERCE_API_BASE_URL', ''),
        'request_timeout' => (int) env('WOOCOMMERCE_REQUEST_TIMEOUT', 30),
        'webhook_debounce_seconds' => (int) env('WOOCOMMERCE_WEBHOOK_DEBOUNCE_SECONDS', 120),
        'order_page_size' => (int) env('WOOCOMMERCE_ORDER_PAGE_SIZE', 25),
        'product_page_size' => (int) env('WOOCOMMERCE_PRODUCT_PAGE_SIZE', 25),
        'max_pages_per_sync' => (int) env('WOOCOMMERCE_MAX_PAGES_PER_SYNC', 10),
        'batch_size' => (int) env('WOOCOMMERCE_BATCH_SIZE', 25),
        'batch_push_enabled' => (bool) env('WOOCOMMERCE_BATCH_PUSH_ENABLED', true),
        'version' => env('WOOCOMMERCE_API_VERSION', 'wc/v3'),
        'order_fields' => [
            'id',
            'number',
            'status',
            'date_created',
            'date_created_gmt',
            'date_modified',
            'date_modified_gmt',
            'billing',
            'shipping',
            'shipping_lines',
            'line_items',
        ],
        'product_fields' => [
            'id',
            'parent_id',
            'sku',
            'name',
            'status',
            'price',
            'regular_price',
            'manage_stock',
            'stock_quantity',
            'date_created',
            'date_created_gmt',
            'date_modified',
            'date_modified_gmt',
            'categories',
            'brands',
        ],
        'sync_defaults' => [
            'orders_poll_minutes' => 30,
            'finance_poll_minutes' => 360,
            'products_poll_minutes' => 720,
            'backfill_mode' => '7_days',
            'backfill_days' => 7,
            'finance_enabled' => false,
            'price_push_enabled' => false,
            'stock_push_enabled' => false,
            'max_parallel_jobs' => 1,
            'request_jitter_seconds' => 15,
        ],
    ],

    'shopify' => [
        'base_url' => env('SHOPIFY_API_BASE_URL', ''),
        'request_timeout' => (int) env('SHOPIFY_REQUEST_TIMEOUT', 45),
        'webhook_debounce_seconds' => (int) env('SHOPIFY_WEBHOOK_DEBOUNCE_SECONDS', 45),
        'api_version' => env('SHOPIFY_API_VERSION', '2025-10'),
        'order_page_size' => (int) env('SHOPIFY_ORDER_PAGE_SIZE', 50),
        'product_page_size' => (int) env('SHOPIFY_PRODUCT_PAGE_SIZE', 50),
        'finance_page_size' => (int) env('SHOPIFY_FINANCE_PAGE_SIZE', 25),
        'sync_defaults' => [
            'orders_poll_minutes' => 20,
            'finance_poll_minutes' => 240,
            'products_poll_minutes' => 720,
            'backfill_mode' => '7_days',
            'backfill_days' => 7,
            'price_push_enabled' => false,
            'stock_push_enabled' => false,
            'max_parallel_jobs' => 1,
            'request_jitter_seconds' => 10,
        ],
    ],
];
