<?php
namespace App\Modules\Hr\Engagement\Livewire;
use App\Modules\Hr\Core\Services\TenantContext; use App\Modules\Hr\Engagement\Actions\CreateSurveyAction; use App\Modules\Hr\Engagement\Actions\GiveRecognitionAction; use App\Modules\Hr\Engagement\Actions\SubmitSurveyResponseAction; use App\Modules\Hr\Engagement\Models\HrRecognition; use App\Modules\Hr\Engagement\Models\HrSurvey; use App\Modules\Hr\Engagement\Models\HrSurveyResponse; use App\Modules\Hr\Personnel\Models\HrEmployee; use Livewire\Component;
class EngagementWorkspace extends Component { public bool $selfService=false; public string $title=''; public string $description=''; public string $startsOn=''; public string $endsOn=''; public bool $isAnonymous=true; public int $minimumReportCount=3; public string $questionsJson=''; public ?int $answeringSurveyId=null; public array $answers=[]; public ?int $recipientEmployeeId=null; public string $recognitionCategory='thanks'; public string $recognitionMessage=''; public bool $recognitionPublic=true;
public function mount(bool $selfService=false):void{$this->selfService=$selfService;$this->startsOn=today()->toDateString();$this->endsOn=today()->addWeeks(2)->toDateString();$this->questionsJson=json_encode([['id'=>'enps','label'=>'ZOLM’u çalışmak için önerme olasılığınız nedir?','type'=>'enps','required'=>true],['id'=>'energy','label'=>'Bu hafta iş enerjinizi nasıl değerlendirirsiniz?','type'=>'scale','required'=>true],['id'=>'comment','label'=>'Neyi iyileştirebiliriz?','type'=>'text','required'=>false]],JSON_UNESCAPED_UNICODE|JSON_PRETTY_PRINT);}
public function createSurvey(CreateSurveyAction $action):void{$questions=json_decode($this->questionsJson,true);abort_unless(is_array($questions),422,'Soru JSON biçimi geçersiz.');$this->validate(['title'=>'required|string|max:180','startsOn'=>'required|date','endsOn'=>'required|date','minimumReportCount'=>'required|integer|min:3|max:50']);$action->execute(['title'=>$this->title,'description'=>$this->description?:null,'starts_on'=>$this->startsOn,'ends_on'=>$this->endsOn,'questions'=>$questions,'is_anonymous'=>$this->isAnonymous,'minimum_report_count'=>$this->minimumReportCount]);$this->reset(['title','description']);session()->flash('success','Nabız anketi oluşturuldu.');}
public function transitionSurvey(int $id,string $status,CreateSurveyAction $action):void{$action->transition($this->survey($id),$status);}
public function openSurvey(int $id):void{$survey=$this->survey($id);abort_unless($survey->status==='active',422);$this->answeringSurveyId=$id;$this->answers=[];}
public function submitSurvey(SubmitSurveyResponseAction $action):void{$survey=$this->survey($this->answeringSurveyId);$action->execute($survey,$this->ownEmployee(),$this->answers);$this->reset(['answeringSurveyId','answers']);session()->flash('success','Yanıtınız kaydedildi.');}
public function giveRecognition(GiveRecognitionAction $action):void{$this->validate(['recipientEmployeeId'=>'required|integer','recognitionMessage'=>'required|string|max:1000']);$action->execute($this->ownEmployee(),$this->employee($this->recipientEmployeeId),$this->recognitionMessage,$this->recognitionCategory,$this->recognitionPublic);$this->reset(['recipientEmployeeId','recognitionMessage']);session()->flash('success','Takdir mesajı paylaşıldı.');}
public function render(){ $tenant=app(TenantContext::class)->getId();$own=HrEmployee::withoutGlobalScope('tenant')->where('legal_entity_id',$tenant)->where('user_id',auth()->id())->first();$surveys=HrSurvey::withoutGlobalScope('tenant')->where('legal_entity_id',$tenant)->withCount('responses')->latest()->get();$hashes=$own?$surveys->mapWithKeys(fn($s)=>[$s->id=>hash_hmac('sha256',$s->id.':'.$own->id,(string)config('app.key'))]):collect();$answered=HrSurveyResponse::withoutGlobalScope('tenant')->where('legal_entity_id',$tenant)->whereIn('respondent_hash',$hashes->values())->pluck('survey_id')->all();$results=[];if(auth()->user()?->hasHrPermission('hr.engagement.manage_surveys'))foreach($surveys as $survey){if($survey->responses_count<$survey->minimum_report_count){$results[$survey->id]=null;continue;}$scores=HrSurveyResponse::withoutGlobalScope('tenant')->where('survey_id',$survey->id)->whereNotNull('enps_score')->pluck('enps_score');$results[$survey->id]=$scores->isEmpty()?null:round(($scores->filter(fn($v)=>$v>=9)->count()/$scores->count()*100)-($scores->filter(fn($v)=>$v<=6)->count()/$scores->count()*100));}$recognitions=HrRecognition::withoutGlobalScope('tenant')->where('legal_entity_id',$tenant)->when($own,fn($q)=>$q->where(fn($w)=>$w->where('is_public',true)->orWhere('sender_employee_id',$own->id)->orWhere('recipient_employee_id',$own->id)),fn($q)=>$q->where('is_public',true))->with(['sender','recipient'])->latest('recognized_at')->limit(40)->get();return view('livewire.hr.engagement.engagement-workspace',['surveys'=>$surveys,'answeredSurveyIds'=>$answered,'surveyResults'=>$results,'recognitions'=>$recognitions,'employees'=>HrEmployee::withoutGlobalScope('tenant')->where('legal_entity_id',$tenant)->active()->when($own,fn($q)=>$q->whereKeyNot($own->id))->orderBy('first_name')->get()])->layout('layouts.app');}
private function survey(?int $id):HrSurvey{abort_unless($id,404);return HrSurvey::withoutGlobalScope('tenant')->where('legal_entity_id',app(TenantContext::class)->getId())->findOrFail($id);}private function employee(?int $id):HrEmployee{return HrEmployee::withoutGlobalScope('tenant')->where('legal_entity_id',app(TenantContext::class)->getId())->findOrFail($id);}private function ownEmployee():HrEmployee{return HrEmployee::withoutGlobalScope('tenant')->where('legal_entity_id',app(TenantContext::class)->getId())->where('user_id',auth()->id())->firstOrFail();}}
