[program:zolm-scheduler]
directory=/var/www/zolm
command=/usr/bin/php artisan schedule:work --no-interaction
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
redirect_stderr=true
stdout_logfile=/var/log/zolm/scheduler.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=10
stopwaitsecs=60

