<div class="space-y-4 lg:space-y-6">
    <div><h1 class="text-xl font-semibold text-slate-900 lg:text-2xl">İSG ve Uyum</h1><p class="mt-1 text-sm text-slate-500">Olay bildirimi, düzeltici aksiyon ve ayrı yetkili sağlık kaydı yüzeyi.</p></div>
    @if(session('success'))<div class="rounded-[8px] border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-800">{{ session('success') }}</div>@endif
    @if($errors->any())<div class="rounded-[8px] border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-800">{{ $errors->first() }}</div>@endif

    @if(auth()->user()?->hasHrPermission('hr.isg.report_incident'))
        <form wire:submit="report" class="rounded-[10px] border border-slate-200 bg-white p-4 shadow-sm lg:p-6">
            <div class="mb-3"><h2 class="text-sm font-semibold">Yeni olay bildirimi</h2><p class="text-xs text-slate-500">Açıklama ve ilk müdahale metni şifreli saklanır.</p></div>
            <div class="grid grid-cols-1 gap-3 sm:grid-cols-2 xl:grid-cols-3">
                <select wire:model.defer="incidentType" class="rounded-[6px] border border-slate-200 px-3 py-3 text-base sm:py-2 sm:text-sm"><option value="near_miss">Ramak kala</option><option value="injury">Yaralanma</option><option value="occupational_disease">Meslek hastalığı</option><option value="unsafe_condition">Güvensiz durum</option><option value="environmental">Çevresel olay</option><option value="other">Diğer</option></select>
                <select wire:model.defer="severity" class="rounded-[6px] border border-slate-200 px-3 py-3 text-base sm:py-2 sm:text-sm"><option value="low">Düşük</option><option value="medium">Orta</option><option value="high">Yüksek</option><option value="critical">Kritik</option></select>
                <input type="datetime-local" wire:model.defer="occurredAt" class="rounded-[6px] border border-slate-200 px-3 py-3 text-base sm:py-2 sm:text-sm">
                <select wire:model.defer="affectedEmployeeId" class="rounded-[6px] border border-slate-200 px-3 py-3 text-base sm:py-2 sm:text-sm"><option value="">Etkilenen çalışan yok / bilinmiyor</option>@foreach($employees as $employee)<option value="{{ $employee->id }}">{{ $employee->full_name }}</option>@endforeach</select>
                <input wire:model.defer="location" class="rounded-[6px] border border-slate-200 px-3 py-3 text-base sm:py-2 sm:text-sm" placeholder="Olay yeri">
                <label class="flex min-h-11 items-center gap-2 rounded-[6px] border border-slate-200 px-3 text-sm"><input type="checkbox" wire:model.defer="lostTime"> İş günü kaybı oluştu</label>
                <textarea wire:model.defer="description" rows="3" class="rounded-[6px] border border-slate-200 px-3 py-3 text-base sm:col-span-2 sm:text-sm" placeholder="Olay açıklaması"></textarea>
                <textarea wire:model.defer="immediateAction" rows="3" class="rounded-[6px] border border-slate-200 px-3 py-3 text-base sm:text-sm" placeholder="İlk müdahale / alınan önlem"></textarea>
                <button class="w-full rounded-[6px] bg-slate-900 px-4 py-3 text-white sm:w-auto sm:py-2">Olayı bildir</button>
            </div>
        </form>
    @endif

    <section class="overflow-hidden rounded-[10px] border border-slate-200 bg-white shadow-sm">
        <div class="flex flex-col gap-3 border-b border-slate-200 bg-slate-50/60 p-4 sm:flex-row sm:items-center sm:justify-between"><div><h2 class="text-sm font-semibold">İSG olay defteri</h2><p class="text-xs text-slate-500">{{ $incidents->count() }} olay</p></div><div class="flex gap-2"><select wire:model.live="statusFilter" class="rounded-[6px] border border-slate-200 bg-white px-3 py-3 text-base sm:py-2 sm:text-sm"><option value="">Tüm durumlar</option><option value="reported">Bildirildi</option><option value="investigating">İnceleniyor</option><option value="action_required">Aksiyon gerekli</option><option value="closed">Kapalı</option></select><div class="relative" x-data="{ open: false }"><button @click="open = !open" type="button" class="rounded-[6px] border border-slate-200 bg-white px-3 py-3 text-sm sm:py-2">Kolonlar · {{ count($visibleColumns) }}</button><div x-show="open" x-cloak @click.outside="open = false" class="absolute right-0 z-20 mt-2 w-48 rounded-[8px] border border-slate-200 bg-white p-3 shadow-md">@foreach($columnLabels as $key => $label)<label class="flex gap-2 py-1 text-xs"><input type="checkbox" wire:click="toggleColumn('{{ $key }}')" @checked(in_array($key, $visibleColumns, true)) @disabled(in_array($key, ['number', 'actions'], true))>{{ $label }}</label>@endforeach</div></div></div></div>
        <div class="hidden overflow-x-auto rounded-lg md:block" x-data="columnResize()"><table class="w-full table-fixed" style="min-width: 850px"><thead class="bg-slate-50/60 text-left text-xs uppercase text-slate-500"><tr>@foreach($columnLabels as $key => $label)@if(in_array($key, $visibleColumns, true))<th class="relative px-4 py-3" style="width: {{ in_array($key, ['location', 'actions'], true) ? '170px' : '125px' }}">@if(isset($sortableColumns[$key]))<button wire:click="sortTable('{{ $key }}')">{{ $label }} @if($sortField === $sortableColumns[$key]){{ $sortDirection === 'asc' ? '↑' : '↓' }}@endif</button>@else{{ $label }}@endif<span class="col-resize-handle" @mousedown.prevent="startResize($event, $el.parentElement)"></span></th>@endif @endforeach</tr></thead><tbody class="divide-y divide-slate-100">@forelse($incidents as $incident)<tr wire:click="select({{ $incident->id }})" class="cursor-pointer hover:bg-slate-50/60 {{ $selectedIncidentId === $incident->id ? 'bg-slate-50' : '' }}">@if(in_array('number', $visibleColumns, true))<td class="overflow-hidden text-ellipsis px-4 py-3 text-xs font-mono">{{ $incident->incident_number }}</td>@endif @if(in_array('type', $visibleColumns, true))<td class="px-4 py-3 text-sm">{{ $incident->incident_type }}</td>@endif @if(in_array('severity', $visibleColumns, true))<td class="px-4 py-3"><span class="rounded px-2 py-0.5 text-xs font-mono {{ $incident->severity === 'critical' ? 'bg-red-50 text-red-700' : ($incident->severity === 'high' ? 'bg-amber-50 text-amber-700' : 'bg-slate-100') }}">{{ $incident->severity }}</span></td>@endif @if(in_array('occurred', $visibleColumns, true))<td class="px-4 py-3 text-xs">{{ $incident->occurred_at->format('d.m.Y H:i') }}</td>@endif @if(in_array('location', $visibleColumns, true))<td class="overflow-hidden text-ellipsis px-4 py-3 text-sm">{{ $incident->location }}</td>@endif @if(in_array('status', $visibleColumns, true))<td class="px-4 py-3 text-xs">{{ $incident->status }}</td>@endif @if(in_array('actions', $visibleColumns, true))<td class="px-4 py-3 text-xs">{{ $incident->pending_actions_count }}/{{ $incident->actions_count }} açık</td>@endif</tr>@empty<tr><td colspan="{{ count($visibleColumns) }}" class="p-10 text-center text-sm text-slate-500">İSG olayı bulunamadı.</td></tr>@endforelse</tbody></table></div>
        <div class="divide-y divide-slate-100 md:hidden">@forelse($incidents as $incident)<button wire:click="select({{ $incident->id }})" class="w-full p-4 text-left"><div class="flex justify-between gap-3"><div class="min-w-0"><p class="truncate text-sm font-medium">{{ $incident->incident_number }} · {{ $incident->location }}</p><p class="mt-1 text-xs text-slate-500">{{ $incident->incident_type }} · {{ $incident->occurred_at->format('d.m.Y H:i') }}</p></div><span class="rounded bg-slate-100 px-2 py-0.5 text-xs font-mono">{{ $incident->status }}</span></div></button>@empty<p class="p-8 text-center text-sm text-slate-500">İSG olayı bulunamadı.</p>@endforelse</div>
    </section>

    @if($selected)
        <section class="overflow-hidden rounded-[10px] border border-slate-200 bg-white shadow-sm"><div class="flex flex-col gap-3 border-b border-slate-200 bg-slate-50/60 p-4 sm:flex-row sm:items-center sm:justify-between"><div class="min-w-0"><h2 class="truncate text-sm font-semibold">{{ $selected->incident_number }} · {{ $selected->location }}</h2><p class="mt-1 text-xs text-slate-500">{{ $selected->severity }} · {{ $selected->status }} · kaynak {{ substr($selected->source_hash, 0, 12) }}</p></div>@if(auth()->user()?->hasHrPermission('hr.isg.manage'))<div class="flex gap-2">@if(!$selected->assigned_to && $selected->status !== 'closed')<button wire:click="assignToSelf" class="rounded-[6px] border border-slate-200 bg-white px-3 py-2 text-xs">İncelemeye al</button>@endif @if($selected->status !== 'closed')<button wire:click="closeIncident" wire:confirm="Tüm açık aksiyonlar tamamlandıysa olay kapatılacak. Devam edilsin mi?" class="rounded-[6px] bg-slate-900 px-3 py-2 text-xs text-white">Olayı kapat</button>@endif</div>@endif</div><div class="grid grid-cols-1 gap-3 border-b border-slate-200 p-4 sm:grid-cols-2"><div><p class="text-xs text-slate-500">Olay açıklaması</p><p class="mt-1 whitespace-pre-wrap text-sm">{{ $selected->description() }}</p></div><div><p class="text-xs text-slate-500">İlk müdahale</p><p class="mt-1 whitespace-pre-wrap text-sm">{{ $selected->immediateAction() ?: '—' }}</p></div></div>
            @if(auth()->user()?->hasHrPermission('hr.isg.manage') && $selected->status !== 'closed')<form wire:submit="addCorrectiveAction" class="grid grid-cols-1 gap-3 border-b border-slate-200 p-4 sm:grid-cols-3"><input wire:model.defer="actionTitle" class="rounded-[6px] border border-slate-200 px-3 py-3 text-base sm:col-span-2 sm:py-2 sm:text-sm" placeholder="Düzeltici aksiyon"><input type="date" wire:model.defer="actionDueOn" class="rounded-[6px] border border-slate-200 px-3 py-3 text-base sm:py-2 sm:text-sm"><button class="w-full rounded-[6px] bg-slate-900 px-4 py-3 text-sm text-white sm:w-auto sm:py-2">Aksiyon ekle</button></form>@endif
            <div class="divide-y divide-slate-100">@forelse($selected->actions as $row)<article class="p-4"><div class="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between"><div><p class="text-sm font-medium">{{ $row->title }}</p><p class="text-xs text-slate-500">{{ $row->due_on?->format('d.m.Y') ?? 'Termin yok' }} · {{ $row->status }}</p></div>@if($row->status === 'pending' && auth()->user()?->hasHrPermission('hr.isg.manage'))<div class="flex flex-col gap-2 sm:flex-row"><input wire:model.defer="actionEvidence.{{ $row->id }}" class="rounded-[6px] border border-slate-200 px-3 py-3 text-base sm:py-2 sm:text-sm" placeholder="Tamamlama kanıtı"><button wire:click="completeAction({{ $row->id }})" class="rounded-[6px] border border-slate-200 bg-white px-3 py-2 text-xs">Tamamla</button></div>@elseif($row->status === 'completed')<p class="text-xs text-emerald-700">Kanıtlı tamamlandı</p>@endif</div></article>@empty<p class="p-6 text-sm text-slate-500">Düzeltici aksiyon yok.</p>@endforelse</div>
        </section>
    @endif

    @if(auth()->user()?->hasHrPermission('hr.isg.view_health'))
        <section class="overflow-hidden rounded-[10px] border border-slate-200 bg-white shadow-sm"><div class="border-b border-slate-200 bg-slate-50/60 p-4"><h2 class="text-sm font-semibold">Sağlık kayıtları · kısıtlı erişim</h2><p class="text-xs text-slate-500">Bu alan yalnız `hr.isg.view_health` yetkisiyle görüntülenir.</p></div>@if(auth()->user()?->hasHrPermission('hr.isg.manage'))<form wire:submit="createHealthRecord" class="grid grid-cols-1 gap-3 border-b border-slate-200 p-4 sm:grid-cols-2 xl:grid-cols-3"><select wire:model.defer="healthEmployeeId" class="rounded-[6px] border border-slate-200 px-3 py-3 text-base sm:py-2 sm:text-sm"><option value="">Çalışan</option>@foreach($employees as $employee)<option value="{{ $employee->id }}">{{ $employee->full_name }}</option>@endforeach</select><select wire:model.defer="healthType" class="rounded-[6px] border border-slate-200 px-3 py-3 text-base sm:py-2 sm:text-sm"><option value="periodic_exam">Periyodik muayene</option><option value="fitness">İşe uygunluk</option><option value="restriction">Kısıt</option><option value="vaccination">Aşı</option><option value="other">Diğer</option></select><input type="date" wire:model.defer="healthRecordedOn" class="rounded-[6px] border border-slate-200 px-3 py-3 text-base sm:py-2 sm:text-sm"><input type="date" wire:model.defer="healthExpiresOn" class="rounded-[6px] border border-slate-200 px-3 py-3 text-base sm:py-2 sm:text-sm"><input wire:model.defer="healthProvider" class="rounded-[6px] border border-slate-200 px-3 py-3 text-base sm:py-2 sm:text-sm" placeholder="Sağlık kuruluşu"><input wire:model.defer="healthResult" class="rounded-[6px] border border-slate-200 px-3 py-3 text-base sm:py-2 sm:text-sm" placeholder="Sonuç"><textarea wire:model.defer="healthDetails" class="rounded-[6px] border border-slate-200 px-3 py-3 text-base sm:col-span-2 sm:text-sm" placeholder="Kısıtlı sağlık detayı"></textarea><button class="w-full rounded-[6px] bg-slate-900 px-4 py-3 text-white sm:w-auto sm:py-2">Sağlık kaydı ekle</button></form>@endif<div class="divide-y divide-slate-100">@forelse($healthRecords as $record)<article class="grid grid-cols-1 gap-2 p-4 sm:grid-cols-3"><div><p class="text-sm font-medium">{{ $record->employee?->full_name }}</p><p class="text-xs text-slate-500">{{ $record->record_type }}</p></div><p class="text-sm">{{ $record->result_encrypted }}</p><p class="text-xs text-slate-500 sm:text-right">{{ $record->recorded_on->format('d.m.Y') }} @if($record->expires_on) · {{ $record->expires_on->format('d.m.Y') }} son @endif</p></article>@empty<p class="p-6 text-sm text-slate-500">Sağlık kaydı yok.</p>@endforelse</div></section>
    @endif
</div>
