<?php

namespace App\Modules\Hr\Asset\Livewire;

use App\Modules\Hr\Asset\Actions\AcceptAssetAssignmentAction;
use App\Modules\Hr\Asset\Actions\AssignAssetAction;
use App\Modules\Hr\Asset\Actions\CreateAssetAction;
use App\Modules\Hr\Asset\Actions\ReturnAssetAction;
use App\Modules\Hr\Asset\Models\HrAsset;
use App\Modules\Hr\Asset\Models\HrAssetAssignment;
use App\Modules\Hr\Asset\Models\HrAssetCategory;
use App\Modules\Hr\Core\Services\TenantContext;
use App\Modules\Hr\Personnel\Models\HrEmployee;
use Livewire\Component;
use Livewire\WithPagination;

class AssetWorkspace extends Component
{
    use WithPagination;
    public bool $selfService=false; public ?int $categoryId=null; public string $assetCode=''; public string $name=''; public string $brand=''; public string $model=''; public string $serialNumber=''; public string $barcode=''; public string $stockItemReference=''; public string $purchasedAt=''; public string $purchaseValue=''; public string $currency='TRY'; public string $notes=''; public string $categoryCode=''; public string $categoryName=''; public string $search=''; public string $statusFilter=''; public string $sortField='asset_code'; public string $sortDirection='asc'; public array $visibleColumns=['code','asset','category','serial','holder','status','actions']; public ?int $assigningId=null; public ?int $employeeId=null; public string $assignedAt=''; public string $expectedReturnAt=''; public string $assignmentNote=''; public ?int $returningId=null; public string $returnCondition='good'; public string $returnNote=''; public bool $markLost=false;
    public const COLUMNS=['code'=>'Kod','asset'=>'Zimmet','category'=>'Kategori','serial'=>'Seri / barkod','holder'=>'Çalışan','status'=>'Durum','actions'=>'İşlem']; private const SORTABLE=['asset_code','name','status','created_at'];

    public function mount(bool $selfService=false):void { $this->selfService=$selfService; $this->assignedAt=today()->toDateString(); }
    public function saveCategory():void { abort_unless(auth()->user()?->hasHrPermission('hr.assets.manage'),403); $this->validate(['categoryCode'=>'required|string|max:60','categoryName'=>'required|string|max:160']); $tenant=app(TenantContext::class)->getId(); $code=strtoupper(trim($this->categoryCode)); abort_if(HrAssetCategory::withoutGlobalScope('tenant')->where('legal_entity_id',$tenant)->where('code',$code)->exists(),422,'Kategori kodu kullanılıyor.'); HrAssetCategory::create(['legal_entity_id'=>$tenant,'code'=>$code,'name'=>trim($this->categoryName),'is_active'=>true,'created_by'=>auth()->id()]); $this->reset(['categoryCode','categoryName']); }
    public function create(CreateAssetAction $action):void { $this->validate(['categoryId'=>'required|integer','assetCode'=>'required|string|max:80','name'=>'required|string|max:160','brand'=>'nullable|string|max:120','model'=>'nullable|string|max:120','serialNumber'=>'nullable|string|max:160','barcode'=>'nullable|string|max:160','stockItemReference'=>'nullable|string|max:190','purchasedAt'=>'nullable|date','purchaseValue'=>'nullable|numeric|min:0','currency'=>'required|in:TRY,EUR,USD,GBP']); $action->execute($this->category($this->categoryId),['asset_code'=>$this->assetCode,'name'=>$this->name,'brand'=>$this->brand,'model'=>$this->model,'serial_number'=>$this->serialNumber,'barcode'=>$this->barcode,'stock_item_reference'=>$this->stockItemReference,'purchased_at'=>$this->purchasedAt?:null,'purchase_value'=>$this->purchaseValue?:null,'currency'=>$this->currency,'notes'=>$this->notes]); $this->reset(['categoryId','assetCode','name','brand','model','serialNumber','barcode','stockItemReference','purchasedAt','purchaseValue','notes']); session()->flash('success','Zimmet envantere eklendi.'); }
    public function accept(int $assignmentId,AcceptAssetAssignmentAction $action):void { $action->execute($this->assignment($assignmentId),true); session()->flash('success','Zimmet teslimi dijital olarak onaylandı.'); }
    public function startAssign(int $id):void { $this->assigningId=$this->asset($id)->id; $this->employeeId=null; $this->assignedAt=today()->toDateString(); $this->expectedReturnAt=''; $this->assignmentNote=''; }
    public function assign(AssignAssetAction $action):void { $this->validate(['employeeId'=>'required|integer','assignedAt'=>'required|date','expectedReturnAt'=>'nullable|date|after_or_equal:assignedAt','assignmentNote'=>'nullable|string|max:1000']); $action->execute($this->asset($this->assigningId),$this->employee($this->employeeId),['assigned_at'=>$this->assignedAt,'expected_return_at'=>$this->expectedReturnAt?:null,'note'=>$this->assignmentNote]); $this->reset(['assigningId','employeeId','expectedReturnAt','assignmentNote']); }
    public function startReturn(int $assignmentId):void { $this->returningId=$this->assignment($assignmentId)->id; $this->returnCondition='good'; $this->returnNote=''; $this->markLost=false; }
    public function returnAsset(ReturnAssetAction $action):void { $this->validate(['returnCondition'=>'required|in:new,good,fair,damaged,lost','returnNote'=>'nullable|string|max:1000']); $action->execute($this->assignment($this->returningId),$this->returnCondition,$this->returnNote?:null,$this->markLost); $this->reset(['returningId','returnNote','markLost']); }
    public function sortTable(string $field):void { abort_unless(in_array($field,self::SORTABLE,true),422); if($this->sortField===$field)$this->sortDirection=$this->sortDirection==='asc'?'desc':'asc';else{$this->sortField=$field;$this->sortDirection='asc';} }
    public function toggleColumn(string $key):void { abort_unless(isset(self::COLUMNS[$key]),422); if(in_array($key,['code','actions'],true))return; $this->visibleColumns=in_array($key,$this->visibleColumns,true)?array_values(array_diff($this->visibleColumns,[$key])):array_values(array_intersect(array_keys(self::COLUMNS),[...$this->visibleColumns,$key])); }
    public function render() { $tenant=app(TenantContext::class)->getId(); $query=HrAsset::withoutGlobalScope('tenant')->where('legal_entity_id',$tenant)->with(['category','activeAssignment.employee']); if($this->selfService)$query->whereHas('assignments',fn($a)=>$a->where('employee_id',$this->ownEmployee()->id)); elseif($this->search!=='')$query->where(fn($x)=>$x->where('asset_code','like',"%{$this->search}%")->orWhere('name','like',"%{$this->search}%")->orWhere('serial_number','like',"%{$this->search}%")->orWhere('barcode','like',"%{$this->search}%")); if($this->statusFilter!=='')$query->where('status',$this->statusFilter); return view('livewire.hr.asset.asset-workspace',['assets'=>$query->orderBy($this->sortField,$this->sortDirection)->paginate(20),'categories'=>HrAssetCategory::withoutGlobalScope('tenant')->where('legal_entity_id',$tenant)->where('is_active',true)->orderBy('name')->get(),'employees'=>HrEmployee::withoutGlobalScope('tenant')->where('legal_entity_id',$tenant)->active()->orderBy('first_name')->get(),'columnLabels'=>self::COLUMNS])->layout('layouts.app'); }
    private function asset(?int $id):HrAsset { abort_unless($id,404); return HrAsset::withoutGlobalScope('tenant')->where('legal_entity_id',app(TenantContext::class)->getId())->findOrFail($id); }
    private function category(?int $id):HrAssetCategory { abort_unless($id,404); return HrAssetCategory::withoutGlobalScope('tenant')->where('legal_entity_id',app(TenantContext::class)->getId())->findOrFail($id); }
    private function employee(?int $id):HrEmployee { abort_unless($id,404); return HrEmployee::withoutGlobalScope('tenant')->where('legal_entity_id',app(TenantContext::class)->getId())->findOrFail($id); }
    private function assignment(?int $id):HrAssetAssignment { abort_unless($id,404); return HrAssetAssignment::withoutGlobalScope('tenant')->where('legal_entity_id',app(TenantContext::class)->getId())->findOrFail($id); }
    private function ownEmployee():HrEmployee { return HrEmployee::withoutGlobalScope('tenant')->where('legal_entity_id',app(TenantContext::class)->getId())->where('user_id',auth()->id())->firstOrFail(); }
}
